<?php

/**
 * Add our custom "General Terms of Use" pane to checkout panes at Administration area
 * 
 * @param array $checkout_panes
 */
function custom_commerce_checkout_pane_info_alter(&$checkout_panes) {
  $checkout_panes['digi_commerce_checkout_terms_of_use_pane'] = array(
		'pane_id' => 'digi_commerce_checkout_terms_of_use_pane',
    'title' => t('Felhasználási feltételek'),
    'file' => 'includes/custom.checkout_pane.inc',
    'base' => 'custom_pane',
    'page' => 'disabled',
    'weight' => 0,
    'saved'  => 1,
    'module' => 'custom'
  );
	$checkout_panes['commerce_checkout_field_group__group_tab_private']['name'] = 'Adatkezelési és Felhasználási feltételek';
	$checkout_panes['commerce_checkout_field_group__group_address']['name'] = 'Szerződés adatainak megadása';
	$checkout_panes['customer_profile_billing']['title'] = 'Szerződő adatainak megadása';
	$checkout_panes['checkout_review']['title'] = 'Megadott adatok áttekintése';
}

function custom_pane_checkout_form($form, $form_state, $checkout_pane, $order) {
  $checkout_form['custom_pane_field_display'] = array(
		'#markup' => variable_get('custom_pane_field')['value'],
  );
  return $checkout_form;
}

function custom_form_alter(&$form, &$form_state, $form_id) {
	global $user;
	switch ($form_id) {
      case 'commerce_checkout_pane_settings_form':
          if (!empty($form_state['input'])) {
              $t = $form_state['input']['digi_commerce_checkout_pane_field']['value'];
              variable_set('digi_commerce_checkout_pane_field', $form_state['input']['digi_commerce_checkout_pane_field']['value']);
          }
          break;

      default:
        break;
	}
}