(function(f){function G(a){"$ignore"===a&&(e.define=y,y=null)}function H(a,b,c){c||(c=b,b=[]);g=0;z[a]=!0;p(b,function(){m[a]=c.apply(null,arguments)})}function p(){n.push(arguments);A()}function A(){var a,b,c,d,h,e,f,g;if(n.length){a=n;n=[];e={};k=[];for(b=a.length;b--;){d=[];f=!0;for(c=a[b][0].length;c--;)h=a[b][0][c],h in m?d[c]=m[h]:(e[h]||z[h]||(k.push(h),e[h]=!0),f&&(n.push(a[b]),f=!1));if(f){g=!0;try{a[b][1].apply(null,d)}catch(l){q(l,"runtime")}}}g?A():n.length&&!r&&(r=v(B,100))}}function B(){var a,
b,c,d,e=[];r=C(r);if(!g){w=C(w);for(a=k.length;a--;)d=k[a],t[d]?(k.splice(a,1),2>t[d]&&(t[d]++,e.push(d))):t[d]=1;g=k.length;e.length&&q(Error("Modules '"+e.join("', '")+"' failed to load"),"loadFailed");if(g){w=v(I,6E4);try{b=l.createElement("script"),b.src=J+"//s1.adformdsp.net/stoat/574/s1.adformdsp.net/load/v/0.0.77/e/"+m.$env.$hash()+"/i/"+m.$ignore+"/r:"+k.sort().join(":"),c=l.__gEBTN__("script")[0],b.onerror=K,c.parentNode.insertBefore(b,c)}catch(f){q(f,"script_insert")}}}}function K(){u("response_error",this.src)}function I(){g=
0;B()}function u(a,b,c){var d=[];Math.random()<(c||.03)&&(d.push((x.host||"//track.adform.net")+"/jslog/"),d.push("?src="),d.push(encodeURIComponent(a)),d.push("&msg="),d.push(encodeURIComponent(b)),a=D?new D(1,1):l.createElement("img"),a.src=d.join(""))}function q(a,b){var c=""+(a.stack||a);0>c.indexOf(a.message||"")&&(c=a+"\n"+c);v(function(){throw c;},0);u(b,c)}function E(){for(var a=arguments,b=0,c=a.length,d=[];b<c;b++)L(a[b])||d.push(a[b]);return d.length?F.apply(e,d):e.length}function L(a){function b(b){b.apply(null,
a.slice(1))}var c=a[0],d=m[c];d?b(d):p([c],b)}var y,F,r,w,k,e=f._adfq||(f._adfq=[]),l=f.document,v=f.setTimeout,C=f.clearTimeout,D=f.Image,x=f.Adform,J="https:"===(x&&(x.shost||"").split("/")[0]||f.location.protocol)?"https:":"http:",m={require:p,$boot:{window:f,require:p,rethrow:q,log:u,deprecate:function(a,b,c){var d=!1;return function(){d||(u("deprecate",b,c),d=!0);return a.apply(this,arguments)}}}},g=0,n=[],z={},t={};l.__gEBTN__=l.getElementsByTagName;(function(){var a;e.define?e.define=G:(F=
e.push,e.define=H,e.push=E,a=e.slice(),e.length=0,E.apply(e,a))})()})(window);
(function(a,e,c,b,v,H,F,G,E,C,D,B,u){
a(e,[c],function(c){c=c.window;var a=c.Adform||{},d=a.ET||{},b=a.RMB||{},e=b.Content||{};b.Type=b.Type||{};b.Content=e;a.ET=d;a.RMB=b;return c.Adform=a});
a(b,[c],function(S){function F(f){return f}function V(){function f(){for(var p=1,b=n;p<k.length&&!k[p];p++)b=b.parent;try{return b==b.Function("return window")()}catch(a){}}function q(p,b){var a=b.charAt(0).toUpperCase()+b.slice(1);return r(p,b,"ms"+a,"moz"+a,"webkit"+a)}function r(a){for(var b=arguments,c=b.length;--c;)if(b[c]in a)return b[c]}function c(a,b){return 0<=(""+a).toLowerCase().indexOf(b.toLowerCase())}var e=S.window,d=e.document,t=d.documentElement,u=e.navigator,n=e.parent,g=
u.vendor,a=u.userAgent,v=d.createElement("div"),k=function(a){for(var b,c=100,e=a.top,d=[!0];--c&&a&&a!=e&&a!=a.parent;){try{b=!!(a=a.parent).Image}catch(f){b=!1}d.push(b)}return d}(e),l=e!=n,G=!l||k[1],B=!l||k[k.length-1],H=l&&f(),A=function(){var a,b=u.plugins,c=u.mimeTypes,d=e.ActiveXObject,f=26,b=b&&b["Shockwave Flash"]&&(!c||!c["application/x-shockwave-flash"]||c["application/x-shockwave-flash"].enabledPlugin)&&(b["Shockwave Flash"].version||b["Shockwave Flash"].description)||"";if(!b&&d)for(;6<=
f--;)try{a=new d("ShockwaveFlash.ShockwaveFlash."+f);6==f&&(a.AllowScriptAccess="always",b="WIN 6.0.21.0");try{b=a.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(g){}return parseFloat(b.replace(/^.*?(\d+[\.,].*$)/,"$1").replace(/(^\d+\.)|\./g,"$1"))||0}(),w=10.3<=A&&!B,T=q(d,"hidden"),I=!!T,m=/MSIE|Trident/i.test(a),U=m&&("Microsoft Internet Explorer"===u.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))?parseFloat(RegExp.$1):-1,v=r(v,"addEventListener"),x=c(g,"apple computer"),
C=c(a,"ipad"),D=c(a,"iphone"),y=C||D,h;h=y&&(h=/\sos\s(\d+)_\d+/i.exec(a))&&(h=4<h[1]>>0);var E=c(g,"google"),J=!y&&c(a,"android"),K="ontouchstart"in d||"ontouchstart"in e,L=(x||E)&&/(chrome|crios)+\/[\d\.]+\s/i.test(a),M=/Firefox\/[\d\.]+/i.test(a),N=c(a,"opera"),g=c(a,"opr")&&c(g,"opera software"),z=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&x,a=m&&(c(a,"IEMobile")||c(a,"WPDesktop")),O=z&&!("webkitRequestAnimationFrame"in e),P="screenX"in e,Q="outerWidth"in e,R="mozInnerScreenX"in
e,t=t.msContentZoomFactor,d=!(!d.fireEvent||!d.attachEvent),F=q(e,"requestAnimationFrame"),w=w&&!z&&(!m||11<=U);return{result:[l,G,B,H,w,I,m,v,x,C,D,y,h,E,J,K,L,M,N,g,z,a,O,P,Q,R,t,d,!1],exports:{nop:function(){},access:k,frame:l,accParent:G,accTop:B,isolate:H,flashVersion:A,flInScreen:w,hidden:T,hasHidden:I,isIE:m,ieVersion:U,addEvent:v,isApple:x,isIPad:C,isIPhone:D,isIOS:y,isIOSF:h,isGoogle:E,isAndroid:J,isTouch:K,isChrome:L,isFirefox:M,isOpera:N,isOperaWebkit:g,isSafari:z,isIEMobile:a,isSafari5OrLess:O,
screenX:P,outerWidth:Q,mozInnerScreenX:R,msZF:t,ieDomEvents:d,reqAni:F,isRad:!1,frame:l,accParent:G,accTop:B,isolate:H,flInScreen:w,hasHidden:I,isIE:m,addEvent:v,isApple:x,isIPad:C,isIPhone:D,isIOS:y,isIOSF:h,isGoogle:E,isAndroid:J,isTouch:K,isChrome:L,isFirefox:M,isOpera:N,isOperaWebkit:g,isSafari:z,isIEMobile:a,isSafari5OrLess:O,screenX:P,outerWidth:Q,mozInnerScreenX:R,msZF:t,ieDomEvents:d,isRad:!1}}}var A={$hash:function(){if(!n){for(var f=V(),q=f.result,f=f.exports,r=[],c=0,e=q.length,d=0,e=e+
(6-e%6)%6;c<e;c++)d=d<<1|!!q[c],5==c%6&&(r.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(d)),d=0);for(c in f)A[c]=f[c];n=r.join("")}return n}},n;try{if(!Function("return ("+F+")(1)===1")())throw"Incorrect eval result";}catch(f){S.log("toString",f)}return A});
a(v,[c,b],function(m,d){var h=m.window,u=h.document,v=h.setTimeout;d.$hash();return function(a){var b,c,e,k,f,g,h=new Date;c=a.type;var n=a.placeId,w=/\.js(\?|$)/i,x=/\.swf(\?|$)/i,l=d.isIE,p=d.flashVersion,q=l&&10>d.ieVersion,l=!l&&21>p;b="standard"==a.type&&"flash"==a.subtype;var y=d.isSafari&&6.1<=d.safariVersion&&b,z=a.fVer||a.ADFVer||a.version,A=a.ADFPoliteSrc,r=a.sources||a.videoSources,t=["src","ADFFlash","ADFInitFlash","bsrc","ADFBuckup"];c=4==a.behavior?"Slider":c.charAt(0).toUpperCase()+
c.slice(1);b=["AdConstructor","types/"+c];if("Standard"==c){for(c=0;c<t.length;c++)(e=a[t[c]])&&(e.match(x)?k=e:e.match(w)?f=e:g=e);g&&q&&(f=0);g&&q&&(r=0);if(z>p||(g||f)&&(l||y))k=0;k?b.push("contents/FlashTag"):f?b.push("contents/HTML"):r&&b.push("contents/VideoTag");(!k&&!f&&g||A)&&b.push("contents/ImageTag")}m.require(b,function B(c){var b,d=c.cbuild;if(n)if(b=u.getElementById(n))a.placement=b.nextSibling||b.previousSibling,b.parentNode.removeChild(b),d(a);else if(1E4>new Date-h)v(function(){B(c)},
0);else throw Error("Failed to find placement");else d(a)})}});
a(H,[c,e],function(f,g){function e(a){return h(a).random()}function h(a){var e={random:k,int32:function(){var b,a,e=[0,2567483615];if(624<=c)for(a=c=0;624>a;a++)b=d[a]&2147483648|d[(a+1)%624]&2147483647,d[a]=d[(a+397)%624]^b>>>1^e[b&1];b=d[c++];b^=b>>>11;b^=b<<7&2636928640;b^=b<<15&4022730752;return(b^b>>>18)>>>0}},d=[],c;a||(a=Math.round(1E5*((new Date).getTime()+Math.random())));d[0]=a>>>0;for(c=1;a=c-1,624>c;c++)a=d[a]^d[a]>>>30,d[c]=(1812433253*((a&4294901760)>>>16)<<16)+1812433253*
(a&65535)+c,d[c]>>>=0;return e}function k(){return Math.floor(this.int32()/65535)}g.random=f.deprecate(e,"Adform.random is deprecated. Use h/random instead.");return e});
a(F,[c,e],function(f,a){function l(a,c){(c?9==c.nodeType?c:c.document:m).write('<script type="text/javascript" src="'+a+'">\x3c/script>')}function n(f){for(var c=a._prepareBannerDataCB,h={},d="ADFVideoCDN ADFDomainCDN ADFDomain VideoCDN ADFVideoCDNList ADFcmpgnID ADFmembID ADFtagID ADFafbanID ADFBanVer ADFBanVerBak ADFbanID ADFbanPlacID ADFUnloadID ADFClientSiteId ADFGeoData ADFGroupId ADFTemplateVersion ADFTemplateId ADF_ClickEvent".split(" "),e=d.length-1;0<=e;e--)d[e]in g&&(h[d[e]]=
g[d[e]]);var k=a.RMBData={clicktags:""};a._prepareBannerDataCB=function(){for(var b=d.length-1;0<=b;b--)d[b]in h&&(g[d[b]]=h[d[b]]);a.prepareBannerData(f);for(b in k)a.RMBData[b]="clicktags"!=b?k[b]:a.RMBData[b]+k[b];c&&c()};c||l(a.scriptBase+"bootstrap/Adform.BannerData.js?v="+a.cache)}var g=f.window,m=g.document;a.host&&(ADFDynamicDomain=a.host+"/banners/");a.shost&&(ADFTemplateDomain=a.shost+"/banners/");a.ENV={akamaiHost:("https:"==m.location.protocol?"https://":"http://")+"adformvod-vh.akamaihd.net/i/Banners"};
a.Log=a.Log||{sendMessage:f.log};a.loadResource=a.loadResource||l;a.prepareBannerData=a.prepareBannerData||n;return{loadResource:a.loadResource,prepareBannerData:a.prepareBannerData}});
a(G,function(){function f(a){a=a||"";var b=a.split(";oobclicktrack=");b.shift();b.length&&(this.tracks=b);a=a.split("?");this._base=a.shift();this._parts=a.join("?").split(";");this.append=[]}function g(a,b,c){var d=a.length;b+="=";var e,f=b.length;for(c||(b=b.toLowerCase());d--&&(e=a[d].slice(0,f),c||(e=e.toLowerCase()),e!==b););return d}var h=Object.prototype.hasOwnProperty,e=f.prototype;e.copy=function(){var a,b=new f;for(a in this)h.call(this,a)&&(b[a]=this[a]&&this[a].slice?this[a].slice(0):
this[a]);return b};e.get=function(a,b){var c=this._parts,d=g(c,a,b);if(~d)return c[d].slice(a.length+1)};e.set=function(a,b,c){var d=this._parts;c=g(d,a,c);0>c?d.push(a+"="+b):d[c]=d[c].slice(0,a.length+1)+b;return this};e.unset=function(a,b){var c=this._parts,d=g(c,a,b);~d&&c.splice(d,1);return this};e.toString=function(){return this._base+"?"+this._parts.join(";")+this.append.join("")};return f});
a(E,[c,b,e,v,H,F,G],function(A,I,e,U,B,f,V){function t(){var a,b;if(u)return u;this.banners={};this.compoundBanners={};try{h.body||h.write("<html><body></body></html>")}catch(c){}a=m.browserLanguage||m.language||0;b=this.getWin();this.settings=[escape(m.systemLanguage||a),escape(a),r?r.width+"X"+r.height:0,I.flashVersion,50*Math.round(b.w/50),50*Math.round(b.h/50),r?r.colorDepth:0,8,3,7,this.hasIframeSanbox()].join("|")}function J(a){var b=
a.placeId="+ADFP"+a.adfxid;h.write('<i id="'+b+'" style="display:none"></i>');A.require(["types/ThirdParty"],function(b){b(a)})}function K(){var a,b,c,d=e.BannerList&&e.BannerList.shift()||e.RMBData;d&&(a=d.type,b=d.behavior,c=d.adfxid||d.ADFid,d._beforeScript=e._beforeScript,e._beforeScript=!1,{standard:1,expanding:1,singleExpanding:1}[a]&&![0,0,0,1,1][b]&&(d.placeId="+ADFP"+c,a=u.banners[c],h.write('<div id="'+d.placeId+'"'+(a.singleTag?"":' style="width:'+a.width+"px;height:"+a.height+'px;"')+
'></div><i style="display:none"></i>')),U(d))}function L(a,b,c){var d=(c=c||h).createElement("div");d.innerHTML='<iframe src="'+a+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" style="'+b+'"></iframe>';c.body.appendChild(d.removeChild(d.firstChild))}function M(a){var b,c,d,f=/\/adfscript/,l=e.ADFIframe&&{src:g.location.href.replace(/cpjs=2/,"cpjs=0")};if(!l)for(b=h.getElementsByTagName("script"),
c=b.length;c--&&!l;)(d=b[c]).src&&d.src.match(f)&&-1<d.src.indexOf(a)&&(l=d);return l||{}}function W(a){var b,c;c=g._adform&&g._adform.tagFrame;var d=a;if("undefined"!=typeof a.URL){try{b=g.top.location.href.split("#")[0]}catch(e){b=c||g,c=(c=b.location.ancestorOrigins)&&c[c.length-1],b=b.document.referrer||c}b=b?w(b):a.CREFURL;d=new V(a.URL);d.append.push("&CREFURL="+b);d.CREFURL=b;d.BN=a.BN;d.ROTSEQ=a.ROTSEQ}return d}function C(a,b){try{if(a){(b=b||[]).push(a);for(var c=0;c<a.frames.length;c++)C(a.frames[c],
b);return b}}catch(d){}}function N(a){return B(a+this.id)}function O(a){try{return a.Adform&&a.Adform.ADFUtilInstance}catch(b){}}function P(a){("undefined"==typeof D?h.createElement("img"):new D).src=a}function E(){return(new Date).getTime()}function Q(a){try{return X(a)}catch(b){return a}}var u,k,F,G,x,g=A.window,h=g.document,m=g.navigator,r=g.screen,Y=g.setTimeout,D=g.Image,R=Object.prototype.hasOwnProperty,y=f.loadResource,w=g.encodeURIComponent,X=g.decodeURIComponent,S=e.cache,H=[];f=t.prototype;
var T={webkitVisibilityState:"webkitvisibilitychange",mozVisibilityState:"mozvisibilitychange",msVisibilityState:"msvisibilitychange",visibilityState:"visibilitychange"};if(e.ADFBannerUtils)return e.ADFBannerUtils;for(x in T)x in h&&(F=x,G=T[x]);f.getCompoundBannerInfo=function(a){return this.compoundBanners["c"+a]||null};f.createBanner=function(a){function b(a){var b=a.url;"stubFileExists"in n||(a.helper&&Y(function(){e.Log.sendMessage("StubFileError","Cref: "+v+" > Adfserve: "+z+" > bn: "+p)},100),
(n.stubFileExists=a.exists)?(b=Q(b),L(e.scriptBase+"iframe/recache.html?bv="+S,"position:absolute;width:10px;height:10px;left:-9999px;top:-9999px"),L(b+"#"+S+"#"+M(p).src,"position:absolute;top:0;left:0;width:100%;height:100%",g._adform&&g._adform.tagFrame&&g.parent.document)):((c=e.RMB)&&(c=c.AdConstructor)&&(c=c.cbuild)||(e.RMB=e.RMB||{},e.RMB.AdConstructor={build:K},e.thirdPartyCB=J),y(z)))}var c,d,f,l,z,q=this,k=q.getTagID(),n=q.addNewBanner(k,"undefined"==typeof e.ADFIframe?0:1);a=n.params=W(a,
q);l=a.get("compoundSeqNo");var p=a.BN,m=q.getCompoundBannerInfo(p),r=q.getPropByBn("smid",p),t=a.ROTSEQ,v=a.CREFURL;a.tracks&&(n.msn=1,n.OOBClickTracks=a.tracks);a.get("singleTag")&&(n.singleTag=!0,l=l||1,a.set("compoundSeqNo",l));n.compoundSeqNo=l;"prerender"==h[F]&&(a.set("hid",2),n.prerender=!0,h.addEventListener(G,function(){"prerender"!=h[F]&&n.prerender&&(h.removeEventListener(G,arguments.callee,!1),q.registerImpression(n))},!1));l&&(l=q.getRotSeed(),d=l.gen(p),l.compound[p]?f=l.compound[p]:
t&&(l.compound[p]=t));a.set("js",1);a.set("adfxid",k);a.set(Math.floor(11E3*Math.random())+";set",q.settings);d&&a.set("rotseed",d);f&&a.set("rotseq",w(f));m&&a.set("rotseqno",m.replace("r",""));r&&a.set("smid",r);e.CDNHost&&a.set("cdnhost",w(e.CDNHost));z=a.toString();if(v&&q.needStubFile()&&!e.ADF_STUB)v=Q(v).replace(/(:\/\/[^\/]+\/).*/,"$1"),e.stubFile=b,y(e.host+"/adfstub/?bn="+p+"&CREFURL="+w(v)),y(e.scriptBase+"extra/StubHelper.js?bv="+e.cache);else{if(e.ADF_STUB)try{e.Log.sendMessage("StubFile",
"Banner loaded using stubFile",.1)}catch(u){}(c=e.RMB)&&(c=c.AdConstructor)&&(c=c.cbuild)||(e.RMB=e.RMB||{},e.RMB.AdConstructor={build:K},e.thirdPartyCB=J);y(z)}return n};f.addNewBanner=function(a,b){return this.banners[a]={id:a,type:b,adfserveLoadTime:E()}};f.copyBanner=function(a,b){var c,d=this.banners[a];if(d=d&&d.params||null){d=d.copy();for(c in b)R.call(b,c)&&d.set(c,b[c]);d=this.createBanner(d)}return d};f.wipeOutBanner=function(a){var b=this.banners[a];b&&(k&&(k.id=B(),k.compound&&delete k.compound[b.bn]),
delete this.compoundBanners["c"+b.bn],delete this.banners[a])};f.addBannerAttribute=function(a,b,c){(a=this.banners[a])&&(a[b]=c)};f.getTagID=function(){var a=this.getRotSeed();a.xId||(a.xId=0);return++a.xId+"x"};f.getRotSeed=function(){var a,b,c,d,e;if(!k){try{for(a=C(g.top),b=0,c=a.length;b<c;b++)if(d=a[b],d!=g&&(e=O(d))&&e.getRotSeed){k=e.getRotSeed();break}}catch(f){}k?k.gen=N:k={compound:{},id:B(),gen:N}}return k};f.getFlashVersion=A.deprecate(function(){return I.flashVersion},"Utils_getFlash");
f.getWin=function(){var a=h.documentElement,b=h.body;return{w:g.innerWidth||a&&a.clientWidth||b&&b.clientWidth,h:g.innerHeight||a&&a.clientHeight||b&&b.clientHeight}};f.getSettings=function(){return this.settings};f.firePixel=P;f.fireTargAdPixel=function(a){var b=this.TargAd||{};b[a]||((this.TargAd=b)[a]=!0,a=a.replace("{gmtr}",Math.floor(9999999999*Math.random())).replace("{gmttzd}",(new Date).getTimezoneOffset()),this.firePixel(a))};f.registerImpression=function(a){var b,c;a&&a.prerender&&(b=a.params.copy(),
b.set("hid",1),a.rotseqno&&b.set("rotseqno",a.rotseqno),c=h.createElement("script"),c.src=b.toString(),c.type="text/javascript",h.body.appendChild(c),delete a.prerender)};f.addCompoundBannerInfo=function(a,b){this.compoundBanners["c"+a]="r"+b};f.setBannerRegisteredStatus=function(a){var b,c,d=this.banners[a];d.csImpressionUrl&&P(d.csImpressionUrl);var f=E(),g=f-d.adfserveLoadTime,h=parseInt(d.serverTime,10),k=e.ADFEventsInstance;d.adfserveLoadTime=g;h&&(h+=Math.round(.5*g),d.serverTime=h,d.timeDiff=
h-f);d.registered=1;this.sendLoadMetrics(a);if(d.singleTag&&1==d.compoundSeqNo)for(b=2,c=d.syncMembersCount;b<=c;b++)this.copyBanner(a,{compoundSeqNo:b,compoundImpr:0});try{for(k&&k.register(d),b=0,c=H.length;b<c;b++)H[b].call(this)}catch(m){}};f.onBannerRegisteredStatus=function(a){H.push(a)};f.hasIframeSanbox=function(){var a=this._sandbox;if("number"!=typeof a){a=1;try{g.top.document.getElementById,a=0}catch(b){}this._sandbox=a}return a};f.getPropByBn=function(a,b){var c,d,e=this.banners;for(c in e)if(d=
e[c],d.bn==b&&a in d)return d[a]};f.now=E;f.needStubFile=function(){var a=g.$sf,b=g.parent,c=this._stub,d=g._adform&&g._adform.tagFrame;if(null==c){c=!(g==b||g.inDapMgrIf||g.inDapIF||g.inFIF||a&&a.ext);!c&&d&&(c=!0,b=d.parent);if(c)try{b.document.getElementById,c=!1}catch(e){}this._stub=c}return c};f.getAdfscript=M;f.getUnloadId=function(a){try{for(var b,c,d,e,f=C(g.top),h=f.length;h--;)for(d in b=(c=O(f[h]))&&c.banners,b)if(e=b[d],e.bn==a&&1==e.compoundSeqNo)return e.unloadID}catch(k){}};f.sendLoadMetrics=
function(a){var b,c,d=[],f=this.banners[a],g=[[f,{adfserveLoadTime:"adfserve"}],[e.locationInfo,{Country:"ls",Region:"lr",City:"lc"}]],h=g.length;if(!f.metricsSent&&.1>Math.random()){for(;h--;)for(b in c=g[h][0]||{},a=g[h][1],a)R.call(c,b)&&d.push(a[b]+"="+c[b]);(new D).src=e.host+"/jsmetrics/?"+d.join("&")}f.metricsSent=!0};f.ADFCreateObjectCallback=function(a,b){return function(){b.apply(a,arguments)}};f.eventRegister=function(){};f.getPosition=function(a){for(var b={x:0,y:0};a;)b.x+=a.offsetLeft,
b.y+=a.offsetTop,a=a.offsetParent;return b};f.getScrollXY=function(){var a=h.body,b=h.documentElement,c={x:0,y:0};"number"==typeof g.pageYOffset?(c.y=g.pageYOffset,c.x=g.pageXOffset):a&&(a.scrollLeft||a.scrollTop)?(c.y=a.scrollTop,c.x=a.scrollLeft):b&&(b.scrollLeft||b.scrollTop)&&(c.y=b.scrollTop,c.x=b.scrollLeft);return c};f.getBrowser=function(){try{var a=m.userAgent;return~m.appVersion.indexOf("MSIE")&&0>a.indexOf("Opera")?"MSIE":~a.indexOf("Safari")?"Safari":~a.indexOf("Opera")?"Opera":~a.indexOf("Netscape")?
~m.product.indexOf("Gecko")&&(~m.vendor.indexOf("Firefox")||~a.indexOf("Firefox"))?"Firefox":"Netscape":void 0}catch(b){}};e.ADFUtilInstance=u=new t;return e.ADFBannerUtils=t.getInstance=t});
a(C,[c,e,E],function(a,e,c){var l=Object.prototype.hasOwnProperty,m=a.window,n=m.document;a={Initialized:!1,InitTime:(new Date).getTime(),Host:e.host||("https:"==n.location.protocol?"https://":"http://")+"track.adform.net",callbacks:[],sendEvent:function(p,f,a,c,h){var d,g,b,k;g=Math.round(((new Date).getTime()-this.InitTime)/1E3);b=q.banners[p];k=e.adRegister&&e.adRegister[p];try{this.notifyAboutEvent.apply(this,arguments)}catch(l){}if(!b&&k)d=k.sendEvent(f,a,c,h);
else if(b&&b.isEventsEnabled){d=b.bn;!b._imprID&&1<b.compoundSeqNo&&(b._imprID=q.getUnloadId(d)||b.unloadID);g=["bn",d,"event",f,"time",(0>g?0:3600<g?3600:g)+"","banner",b.ban,"innerbanner",b.innerban,"asset",a,"name",c,"imprid",b._imprID||b.unloadID,"icid",b.cookieID,"adxvars",b.adxvars,"rnd",Math.floor(1E9*Math.random())];b=0;for(d=[];b<g.length;b+=2)(k=g[b+1])&&d.push(g[b]+"="+encodeURIComponent(k));d=this.Host+"/Serving/Event/?"+d.join("&")+(h||"");(m.Image?new m.Image(1,1):n.createElement("img")).src=
d}return d},Initialize:a.deprecate(function(){this.Initialized=!0},"initEvents",1),registerCallback:function(a,f){"function"==typeof a&&this.callbacks.push([a,f])},unregisterCallback:function(a){var f=this.callbacks,c=f.length;if("function"==typeof a)for(;c--;)f[c][0]==a&&f.splice(c,1)},notifyAboutEvent:function(){for(var a=this.callbacks.slice(),c=0,e=a.length;c<e;c++)a[c][0].apply(a[c][1]||this,arguments)}};var q=c();if(c=e.Events){for(var h in a)l.call(a,h)&&!l.call(c,h)&&(c[h]=a[h]);c.sendEvent=
a.sendEvent}else c=e.Events=a;e.ADFEvents2||(e.ADFEvents2=c);return a});
a(D,[c,e],function(g,b){function d(c){try{var e=c.URL,d=c.BN,h,a,m,k;c=/\/adfscript/;var l=b.ADFIframe&&{src:r.location.href.replace(/cpjs=2/,"cpjs=0")};if(!l)for(a=n.getElementsByTagName("script"),m=a.length;m--&&!l;)(k=a[m]).src&&k.src.match(c)&&-1<k.src.indexOf(d)&&(l=k);h=l||{};var f=n.createElement("div");a=h;var p,t,q,u,e=e.split(";");e[0]+=";srctype=4";for(e=e.join(";");a;)p="BODY"==a.nodeName,t="HEAD"==a.nodeName,a=!(p||t)&&a.parentNode;p?(q=h.parentNode,u=h):q=n.body;f.innerHTML=
'<a href="'+b.host+"/C/?bn="+d+';C=0"><img src="'+e+'"></a>';q.insertBefore(f.firstChild,u||null);g.log("fallback",d)}catch(v){g.rethrow(v,"fallback_error")}}var f,r=g.window,n=r.document;g.require(["$ignore"],function(){var c=b.ADFBannerParams;f||(b.ADFUtilInstance||(b.ADFUtilInstance={}),b.ADFBanner||(b.ADFBanner=d),d(c&&c.length?c.shift():b.ADFBannerData))});return{cancel:function(){f=!0},write:d}});
a(B,[c,e,C,D,E],function(e,b,f,d,g){function c(){var a=b.ADFBannerParams;if(a=a&&a.length?a.shift():b.ADFBannerData)try{g().createBanner(a)}catch(c){e.rethrow(c,"create_banner"),d.write(a)}}b.ADFBanner||(b.ADFBanner=c,b.ADFBanner());f.IE=9;d.cancel();return c});
a(u,function(){return"jYPwAAAAgAA"});
})(_adfq.define,"Adform","$boot","$env","$main","h/random","bootstrap/Global","bootstrap/URL","bootstrap/Utils","bootstrap/Events","bootstrap/Fallback","bootstrap/Banner","$ignore");