(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	manifest: [
		{src:"images/Bitmap1044.jpg", id:"Bitmap1044"},
		{src:"images/slide1_internet.jpg", id:"slide1_internet"},
		{src:"images/slide2_internet.jpg", id:"slide2_internet"},
		{src:"images/smallprintarrow.png", id:"smallprintarrow"},
		{src:"images/upc_mobil_banner_640x360.jpg", id:"upc_mobil_banner_640x360"}
	]
};



// symbols:



(lib.Bitmap1044 = function() {
	this.initialize(img.Bitmap1044);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,56,29);


(lib.slide1_internet = function() {
	this.initialize(img.slide1_internet);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,360);


(lib.slide2_internet = function() {
	this.initialize(img.slide2_internet);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,360);


(lib.smallprintarrow = function() {
	this.initialize(img.smallprintarrow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,21,11);


(lib.upc_mobil_banner_640x360 = function() {
	this.initialize(img.upc_mobil_banner_640x360);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,360);


(lib.Tween3444 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.smallprintarrow();
	this.instance.setTransform(-10.5,-5.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.5,-5.5,21,11);


(lib.Tween3344 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Egu3AU8MAAAgp3MBdvAAAMAAAAp3g");
	this.shape.setTransform(44,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-256,-134,600.2,268.1);


(lib.Tween3244 = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("Akciónk 2016. május 3-tól visszavonásig, új, vagy meglévő szolgáltatási csomagjukat magasabb csomagra módosító internet-előfizetőink számára biztosítottak. Az internet szolgáltatások igénybevételéhez, valamint tulajdonságainak optimális kihasználásához szükséges technikai feltételekről szerződéskötést megelőzően érdeklődjön elérhetőségeinken. Az igénybevétel során érzékelhető sebesség függ a vezetékes és/vagy vezeték nélküli hálózati eszközök működési szabványában foglalt specifikációtól. A tájékoztatás nem teljes körű, további részletek az ÁSZF-ben, valamint a www.upc.hu oldalon és a 1421-es telefonszámon.", "11px 'Arial'");
	this.text.lineHeight = 13;
	this.text.lineWidth = 262;
	this.text.setTransform(28,-545.9);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(28,-545.9,266.1,783);


(lib.Tween644 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Bitmap1044();
	this.instance.setTransform(-28,-14.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-28,-14.5,56,29);


(lib.Tween12 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.upc_mobil_banner_640x360();
	this.instance.setTransform(-320,-180);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-320,-180,640,360);


(lib.Tween3 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.slide2_internet();
	this.instance.setTransform(-357.7,-182.3,0.71,0.71);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-357.7,-182.3,454.4,255.6);


(lib.Tween2 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.slide1_internet();
	this.instance.setTransform(-404.6,-181.3,0.71,0.71);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-404.6,-181.3,454.4,255.6);


(lib.Symbol544 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj5GaIAAszIHzAAIAAMzg");
	this.shape.setTransform(25,41);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Symbol244 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC7BYQgMgHgJgMQgIgMgFgRQgDgLgBgcQAAgNAEgZQAFgRAIgNQAJgNAMgGIANgFQAHgCAIAAQAHAAAHACIANAFQAMAHAJAMQAJANAEARQAFAZAAANQgCAcgDALQgEARgJAMQgIAMgNAHQgGADgHABIgOACQgQAAgMgGgADDhFQgIAFgGALQgGAKgDAOQgEAOAAAQQAAARADAOQAEAOAGAKQAGAJAIAFQAJAGALAAQAKAAAJgGQAJgFAGgJQAGgKADgOQADgOAAgRQAAgPgDgOQgDgOgGgKQgGgLgIgFQgJgGgLAAQgLAAgJAFgAAgBbQgKgEgHgEQgHgGAAgFQAAgJAJAAQADAAAHAEQAGAEAFACQAHADAJAAQAIAAAHgDQAIgDAGgHQAHgHAEgOQAFgOABgWQgHAJgJAFQgLAGgOAAQgIAAgHgCIgMgEQgLgFgHgKQgHgGgDgLQgDgJAAgJQAAgKADgKQADgLAHgJQAHgLALgFIAMgFQAHgCAIAAQAPAAALAGQAMAFAIALQAHALAEAQQAEAQAAAVQgBAfgDANQgHAYgFAIQgEAHgFAEQgGAFgGADIgNAFIgQABQgMAAgKgDgAAphGQgHAEgFAIQgEAGgCAIQgCAHAAAHQACARAGAIQAFAFAHADQAIAFAKAAQALAAAIgFQAHgDAFgFQAGgIACgRQAAgHgCgHQgCgIgEgGQgFgIgHgEQgIgEgLAAQgKAAgIAEgAhyBbQgJgEgHgEQgHgGAAgFQAAgJAJAAQADAAAGAEQAGAEAFACQAHADAJAAQAJAAAHgDQAIgDAGgHQAHgHAEgOQAEgOACgWQgHAJgKAFQgLAGgNAAQgIAAgHgCIgNgEQgLgFgHgKQgGgGgDgLQgDgJAAgJQAAgKADgKQADgLAGgJQAHgLALgFIANgFQAHgCAIAAQAOAAAMAGQALAFAIALQAIALAEAQQAEAQAAAVQgCAfgCANQgHAYgGAIQgEAHgFAEQgFAFgGADIgOAFIgQABQgLAAgLgDgAhphGQgHAEgEAIQgFAGgCAIQgCAHAAAHQADARAGAIQAEAFAHADQAIAFALAAQAKAAAIgFQAHgDAFgFQAGgIADgRQAAgHgCgHQgDgIgEgGQgFgIgHgEQgIgEgKAAQgLAAgIAEgAkLBcQgGAAgEgDQgDgDAAgFQAAgHAEgIQADgHAHgIQAIgLAWgWQAWgUAIgKQAGgIADgHQAEgIAAgHQAAgKgDgHQgDgGgGgEQgIgFgOAAQgHAAgJADIgMAFQgJAEgDAAQgIAAAAgIQAAgGAIgFQAJgFAHgCQAMgFAMAAQAIAAAHACQAKACAIAEQAKAGAFAKQAGAQAAALQAAAJgDAIQgDAIgFAIQgIAKgRARQgpAkgJAUIBNAAQAJAAAAAJQAAAJgJAAg");
	this.shape.setTransform(49.9,35.2);

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiqA9IAshyQABgDAEAAQAFAAAAAFIgrBxQgBAEgFAAQgFAAAAgFgADLAxQgGgDgFgGQgEgFgDgHQgCgIAAgJQAAgJACgFQADgIAEgFQAFgGAGgDQAHgCAHAAQAIAAAGACQAHADAEAGQAFAFACAIQADAFAAAJQAAAJgDAIQgCAHgFAGQgEAFgGADQgHACgIAAQgHAAgHgCgADQgOQgEABgDAEQgDAEgCAFQgBAEAAAHQAAAHABAFQACAFADAEQADAEAEADQAEABAFAAQAGAAAEgBQAEgDADgEQADgDABgGQACgFAAgHQAAgHgCgEQgBgFgDgEQgDgEgEgCQgEgBgGAAQgFAAgEACgACYAyQgFgBgEgDQgEgDgCgGQgDgGAAgKIAAglIgGAAQgGAAAAgFQAAgGAGAAIAGAAIAAgRIABgEQACgCADAAQABAAABAAQAAAAABAAQABAAAAABQAAAAABABIABAEIAAARIAUAAQAGAAAAAGQAAAFgGAAIgUAAIAAAlQAAAGABAEQABAEADACQAEADAHAAIAGgBIAFgBQAFAAAAAFQAAAFgGACQgFABgFAAIgKgBgAgFAxQgHgDgEgGQgFgFgCgHQgDgIAAgJQAAgJADgFQACgIAFgFQAEgGAHgDQAFgCAHAAQAHAAAHACQAGADAEAGQAFAFACAIQADAFAAAJQAAAJgCAIQgDAHgEAGQgFAFgGADQgGACgIAAQgHAAgFgCgAgBgOQgEABgDAEQgDAEgCAFQgBAEAAAHQAAAHABAFQACAFADAEQADAEAEADQACABAGAAQAFAAAEgBQAEgDADgEQADgDACgGQACgFAAgHQAAgHgCgEQgCgFgDgEQgDgEgEgCQgEgBgFAAQgGAAgCACgAjIAyQgGgBgDgDQgFgDgCgGQgCgGAAgKIAAglIgHAAQgGAAAAgFQAAgGAGAAIAHAAIAAgRIABgEQABgCAEAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABIABAEIAAARIAUAAQAGAAAAAGQAAAFgGAAIgUAAIAAAlQAAAGACAEQABAEACACQAEADAHAAIAHgBIAEgBQAFAAAAAFQAAAFgGACQgEABgFAAIgKgBgAERAuQgDgDgCgEIgBgSIAAhRQAAgFAGAAQAFAAAAAFIAABRQAAAMACADQABADAGAAQAGAAAAAGQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBABQgCABgDAAQgJAAgEgEgAg1AtIAAgsIgBgHQAAgEgDgDQgCgCgDgBIgKAAIgLABIgGADIAAA5QAAAFgGAAQgGAAAAgFIAAhpQAAgFAGAAQAGAAAAAFIAAAmIAIgEQAFgBAHAAQAIAAAGACQAFABADAEQADAEABAGQACAFAAAFIAAAtQAAAFgGAAQgGAAAAgFgAkkAtIAAhfQAAgHAIAAIAqAAQAGAAAAAFIgBAEQgBACgEAAIgmAAIAAAjIAjAAQAGAAAAAGQAAAFgGAAIgjAAIAAAtQAAAFgGAAQgGAAAAgFgABBAQQgFAAAAgGQAAgFAFAAIAmAAQAGAAAAAFQAAAGgGAAgADNguIAAgCQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAIAZgLIAEgBQAGAAAAAFQAAAEgEABIgZALIgEABQgFAAAAgFgAgEguIAAgCQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAIAXgLIAEgBQAGAAAAAFQAAAEgEABIgZALIgDABQgEAAAAgFg");
	this.shape_1.setTransform(51.7,56.3);

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0024A3").s().p("AAAHyIgBACQgkgTg1ggQhqhAhRhFQgMgJgXgVQhihZgnhTQgphWgLhFQgFgjAAgfQAAhMAchCQAehDA6gzIAZgVQCGhjDlgMIAEAAQB0AGBfAeQBqAhBIA/QA6AzAdBDQAdBCAABMQAAAhgFAhQgLBEgpBXQgnBThiBZQhcBViEBPQg0AggkASg");
	this.shape_2.setTransform(50.8,99.9,1,1,0,0,0,0,49.9);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,101.6,100.1);


(lib.peng333 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADyCYQgGgBgFgEQgEgDgCgHQgDgHAAgKIAAgqIgHAAQgGAAAAgGQAAgFAGgBIAHAAIAAgTQABgGAFAAQAGAAABAGIAAATIAVAAQAHABAAAFQAAAGgHAAIgVAAIAAAqQAAAGACAFQABAEACACQAEADAJABIAGgCIAFgBQAGAAAAAGQAAAFgHACQgFACgFAAQgHAAgEgBgACcCWQgGgEgFgFQgFgGgDgIQgCgIAAgKQAAgKACgIQADgIAFgFQAFgHAHgDQAHgDAJAAQAGAAAHACQAFADAEADQAFAEABAEQACAEAAAFQABAHgEAGQgEAFgHADQgHADgLABIgYACQABAFACAEIAFAIQADADAEACQAEACAGAAQAHgBANgEIAHgCQAFAAAAAGQAAADgGADQgQAHgKAAQgIAAgIgDgACjBPQgFABgDAEQgEAEgCAFQgCAGAAAGIAUgBQAJgBAFgCQAFgCADgCQACgEAAgDQAAgFgFgEIgFgDIgIgBQgGAAgEACgAhDCWQgHgEgFgFQgFgGgCgIQgDgIgBgKQABgKADgIQACgIAFgFQAFgHAHgDQAHgDAJAAQAGAAAHACQAFADAEADQAFAEACAEQABAEAAAFQAAAHgDAGQgEAFgIADQgGADgLABIgXACQAAAFACAEIAFAIIAHAFQAEACAGAAQAHgBANgEIAHgCQAFAAAAAGQAAADgGADQgQAHgKAAQgJAAgGgDgAg9BPQgFABgDAEQgEAEgCAFQgCAGAAAGIAUgBQAJgBAFgCQAGgCABgCQADgEAAgDQAAgFgFgEIgFgDIgIgBQgGAAgEACgAh6CYQgHgBgDgEQgEgDgDgHQgCgHAAgKIAAgqIgIAAQgGAAAAgGQAAgFAGgBIAIAAIAAgTQgBgGAGAAQAGAAAAAGIAAATIAWAAQAGABAAAFQAAAGgGAAIgWAAIAAAqQABAGABAFQACAEACACQAEADAIABIAHgCIAFgBQAFAAABAGQAAAFgIACQgEACgGAAQgGAAgEgBgABpCRIAAguIAAgLQgBgEgDgDQgCgCgEgBIgKgBQgFAAgHACIgHADIAAA/QAAAHgGAAQgHAAABgHIAAhJQAAgFAFgBQAHABAAAFQAKgHALAAQAJAAAGACQAFACAEADQAEAFABAFQACAGAAAJIAAAwQAAAHgGAAQgHAAAAgHgAgECRIAAhJQAAgFAFgBQAFABAAAFIAAAIQACgFAGgFIAHgEQAEgBAFAAIAHABQAGABgBAFQABAGgGAAIgHgBQgKABgFAFQgEAEgCAGQgDAJAAALIAAAgQAAAHgFAAQgFAAAAgHgAiyCRIAAguIAAgLQgCgEgDgDQgCgCgEgBIgKgBQgGAAgGACIgHADIAAA/QAAAHgFAAQgHAAAAgHIAAhJQAAgFAGgBQAGABAAAFQAKgHAMAAQAIAAAGACQAGACADADQAEAFACAFQACAGAAAJIAAAwQAAAHgHAAQgGAAAAgHgAkLCRIAAhqQAAgGAFAAQAHAAgBAGIAABqQABAHgHAAQgFAAAAgHgAEZgbQgIgDgFgGQgFgFgCgJQgDgHAAgLQAAgKADgIQACgHAFgGQAGgGAHgDQAHgEAJAAQAGAAAHADQAGADADADQAEADADAFQABAEAAAEQAAAIgDAGQgEAEgIADQgGADgMABIgXACIACAJIAGAIQADADAEADQAEABAFAAQAJAAAMgEIAGgDQAHAAgBAHQABADgIADQgPAGgLAAQgIAAgGgDgAEfhhQgFABgDAEQgDAEgDAFQgCAFAAAHIAUgBQAJgCAFgCQAFgBACgDQADgDAAgEQAAgEgFgEIgFgDIgIgBQgGAAgEACgABSgbQgGgDgGgGQgFgFgCgJQgDgHAAgLQAAgKADgIQACgHAFgGQAGgGAGgDQAIgEAHAAQAJAAAGAEQAHADAFAGQAFAGADAHQADAJAAAJQAAAKgDAJQgCAIgGAGQgFAFgGADQgIADgIAAQgHAAgIgDgABXhhQgEACgEAEQgDAEgCAHQgBAFAAAHQAAAIABAGQACAGADAEQAEAEAEACQAFACAFAAQAGAAAFgCQAEgCADgEQAEgEACgGQABgGAAgIQAAgHgBgFQgCgHgEgEIgHgGQgFgCgGAAQgFAAgFACgAixgbQgHgDgFgGIgGgKIgBgEQgEgHAAgLQAAgKAEgIIABgCQADgGADgFQAFgGAIgDQAGgEAJAAQAHAAAGADQAGADAEADQAEADACAFQACAEAAAEQAAAIgEAGQgEAEgHADQgHADgLABIgXACIACAJIAGAIQADADADADQAFABAFAAQAIAAAMgEIAHgDQAGAAAAAHQAAADgHADQgPAGgLAAQgIAAgHgDgAirhhQgEABgDAEQgEAEgCAFQgCAFAAAHIAUgBQAJgCAEgCQAGgBACgDQADgDAAgEQAAgEgFgEIgGgDIgIgBQgFAAgFACgAkHgZQgHgCgFgEQgFgCAAgGIAAhrQAAgGAGAAQAGAAABAGIAAAoQAIgFALgBQAIAAAIAEQAHADAFAGQAFAGADAHQACAIAAAKQAAAKgCAIQgDAIgFAGQgGAGgHADQgIADgIAAQgGAAgIgBgAkFhhIgGADIAAA2QAFADANABQAHAAAFgDQAFgCADgFQADgEACgHIACgLQAAgHgDgGQgBgGgDgEQgEgEgFgCQgFgCgFAAQgHAAgGACgAFZgfIAAhJQgBgGAHAAQAFAAAAAGIAAAHQACgFAGgEIAHgEQAEgCAEAAIAIABQAFACAAAFQAAAFgFABIgIgBQgJABgFAEQgEAFgCAGQgCAIgBAMIAAAgQAAAGgFAAQgHAAABgGgADWgfIgFgPQgKgggDgLQgCAPgQArQgDAGgGAAQgDAAgCgBQgCgCgCgEQgFgOgPg4IAAgCQAAgGAGAAQAEAAABAEQAMAvAGAUIAUhBQABgGAGAAQAHAAABAGIAFASQAKAkAEALQAIgUAKguQABgFAFAAQAGAAAAAGIAAAEQgOA2gHAOQgBAEgCACQgDABgDAAQgFAAgEgGgAgNgfIAAhoQAAgJAIABIAYAAQAGgBAHADQAHACAEAFIADABIAEAJQADAFAAAHQAAAJgDAHQgDAHgFAEQgFAFgGABIgMACIgUAAIAAAuQAAAGgGAAQgGAAAAgGgAgBhYIAUAAQAEgBADgBQAEgBADgDQAEgDACgEQABgEAAgHIgBgIIgFgGIgHgFQgEgBgEAAIgUAAgAhxgfIAAhJQAAgGAGAAQAGAAAAAGIAAAHQACgFAFgEIAIgEQADgCAFAAIAHABQAGACAAAFQAAAFgGABIgHgBQgKABgEAEQgEAFgDAGQgCAIAAAMIAAAgQAAAGgGAAQgGAAAAgGgAk6gfIAAhJQAAgGAGAAQAGAAAAAGIAABJQAAAGgGAAQgGAAAAgGgAmHgfIAAhoQAAgJAIABIAuAAQAGgBAAAGQAAAGgGAAIgrAAIAAAmIAoAAQAGABAAAGQAAAFgGABIgoAAIAAAyQAAAGgFAAQgHAAABgGgAk6iEIAAgGQAAgHAGABQAGgBAAAHIAAAGQAAAGgGAAQgGAAAAgGg");
	this.shape.setTransform(50.9,40.9);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#029F32").s().p("AAAHyIgBACQgkgTg1ggQhqhAhRhFQgMgJgXgVQhihZgnhTQgphWgLhFQgFgjAAgfQAAhMAchCQAehDA6gzIAZgVQCGhjDlgMIAEAAQB0AGBfAeQBqAhBIA/QA6AzAdBDQAdBCAABMQAAAhgFAhQgLBEgpBXQgnBThiBZQhcBViEBPQg0AggkASg");
	this.shape_1.setTransform(50.8,99.9,1,1,0,0,0,0,49.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,101.6,100.1);


(lib.hl = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}
	this.frame_79 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(39).call(this.frame_39).wait(40).call(this.frame_79).wait(1));

	// Layer 4 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EggfAJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_1 = new cjs.Graphics().p("EggfAJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_2 = new cjs.Graphics().p("EggMAJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_3 = new cjs.Graphics().p("A+ZJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_4 = new cjs.Graphics().p("A8mJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_5 = new cjs.Graphics().p("A6zJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_6 = new cjs.Graphics().p("A5AJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_7 = new cjs.Graphics().p("A3NJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_8 = new cjs.Graphics().p("A1aJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_9 = new cjs.Graphics().p("AznJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_10 = new cjs.Graphics().p("AxzJYIAAyvMBA+AAAIAASvg");
	var mask_1_graphics_11 = new cjs.Graphics().p("AwAJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_12 = new cjs.Graphics().p("AuNJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_13 = new cjs.Graphics().p("AsaJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_14 = new cjs.Graphics().p("AqnJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_15 = new cjs.Graphics().p("Ao0JYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_16 = new cjs.Graphics().p("AnBJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_17 = new cjs.Graphics().p("AlOJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_18 = new cjs.Graphics().p("AjbJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_19 = new cjs.Graphics().p("AhoJYIAAyvMBA/AAAIAASvg");
	var mask_1_graphics_20 = new cjs.Graphics().p("ALMJYIAAyvMBBBAAAIAASvg");
	var mask_1_graphics_21 = new cjs.Graphics().p("AFQJYIAAyvMBDnAAAIAASvg");
	var mask_1_graphics_22 = new cjs.Graphics().p("AgWJYIAAyvMBGDAAAIAASvg");
	var mask_1_graphics_23 = new cjs.Graphics().p("AlpJYIAAyvMBIXAAAIAASvg");
	var mask_1_graphics_24 = new cjs.Graphics().p("AqoJYIAAyvMBKjAAAIAASvg");
	var mask_1_graphics_25 = new cjs.Graphics().p("AvSJYIAAyvMBMlAAAIAASvg");
	var mask_1_graphics_26 = new cjs.Graphics().p("AznJYIAAyvMBOeAAAIAASvg");
	var mask_1_graphics_27 = new cjs.Graphics().p("A3oJYIAAyvMBQOAAAIAASvg");
	var mask_1_graphics_28 = new cjs.Graphics().p("A7UJYIAAyvMBR1AAAIAASvg");
	var mask_1_graphics_29 = new cjs.Graphics().p("A+sJYIAAyvMBTUAAAIAASvg");
	var mask_1_graphics_30 = new cjs.Graphics().p("EghvAJYIAAyvMBUpAAAIAASvg");
	var mask_1_graphics_31 = new cjs.Graphics().p("EgkeAJYIAAyvMBV2AAAIAASvg");
	var mask_1_graphics_32 = new cjs.Graphics().p("Egm4AJYIAAyvMBW5AAAIAASvg");
	var mask_1_graphics_33 = new cjs.Graphics().p("Ego+AJYIAAyvMBX0AAAIAASvg");
	var mask_1_graphics_34 = new cjs.Graphics().p("EgqvAJYIAAyvMBYlAAAIAASvg");
	var mask_1_graphics_35 = new cjs.Graphics().p("EgsLAJYIAAyvMBZNAAAIAASvg");
	var mask_1_graphics_36 = new cjs.Graphics().p("Egs2AJYIAAyvMBZtAAAIAASvg");
	var mask_1_graphics_37 = new cjs.Graphics().p("EgtBAJYIAAyvMBaDAAAIAASvg");
	var mask_1_graphics_38 = new cjs.Graphics().p("EgtIAJYIAAyvMBaRAAAIAASvg");
	var mask_1_graphics_39 = new cjs.Graphics().p("EgtKAJYIAAyvMBaVAAAIAASvg");
	var mask_1_graphics_40 = new cjs.Graphics().p("Egr8AJYIAAyvMBZfAAAIAASvg");
	var mask_1_graphics_41 = new cjs.Graphics().p("EgpIAJYIAAyvMBYnAAAIAASvg");
	var mask_1_graphics_42 = new cjs.Graphics().p("EgmUAJYIAAyvMBXwAAAIAASvg");
	var mask_1_graphics_43 = new cjs.Graphics().p("EgjgAJYIAAyvMBW4AAAIAASvg");
	var mask_1_graphics_44 = new cjs.Graphics().p("EggsAJYIAAyvMBWBAAAIAASvg");
	var mask_1_graphics_45 = new cjs.Graphics().p("A94JYIAAyvMBVKAAAIAASvg");
	var mask_1_graphics_46 = new cjs.Graphics().p("A7DJYIAAyvMBURAAAIAASvg");
	var mask_1_graphics_47 = new cjs.Graphics().p("A4PJYIAAyvMBTaAAAIAASvg");
	var mask_1_graphics_48 = new cjs.Graphics().p("A1bJYIAAyvMBSiAAAIAASvg");
	var mask_1_graphics_49 = new cjs.Graphics().p("AynJYIAAyvMBRrAAAIAASvg");
	var mask_1_graphics_50 = new cjs.Graphics().p("AvzJYIAAyvMBQzAAAIAASvg");
	var mask_1_graphics_51 = new cjs.Graphics().p("As/JYIAAyvMBP8AAAIAASvg");
	var mask_1_graphics_52 = new cjs.Graphics().p("AqLJYIAAyvMBPFAAAIAASvg");
	var mask_1_graphics_53 = new cjs.Graphics().p("AnXJYIAAyvMBONAAAIAASvg");
	var mask_1_graphics_54 = new cjs.Graphics().p("AkjJYIAAyvMBNWAAAIAASvg");
	var mask_1_graphics_55 = new cjs.Graphics().p("AhvJYIAAyvMBMeAAAIAASvg");
	var mask_1_graphics_56 = new cjs.Graphics().p("ABDJYIAAyvMBLpAAAIAASvg");
	var mask_1_graphics_57 = new cjs.Graphics().p("AD3JYIAAyvMBKyAAAIAASvg");
	var mask_1_graphics_58 = new cjs.Graphics().p("AGrJYIAAyvMBJ6AAAIAASvg");
	var mask_1_graphics_59 = new cjs.Graphics().p("AoOJYIAAyvMBJ4AAAIAASvg");
	var mask_1_graphics_60 = new cjs.Graphics().p("Ar+JYIAAyvMBLmAAAIAASvg");
	var mask_1_graphics_61 = new cjs.Graphics().p("AvjJYIAAyvMBNQAAAIAASvg");
	var mask_1_graphics_62 = new cjs.Graphics().p("Ay7JYIAAyvMBO0AAAIAASvg");
	var mask_1_graphics_63 = new cjs.Graphics().p("A2GJYIAAyvMBQRAAAIAASvg");
	var mask_1_graphics_64 = new cjs.Graphics().p("A5GJYIAAyvMBRqAAAIAASvg");
	var mask_1_graphics_65 = new cjs.Graphics().p("A75JYIAAyvMBS8AAAIAASvg");
	var mask_1_graphics_66 = new cjs.Graphics().p("A+fJYIAAyvMBUIAAAIAASvg");
	var mask_1_graphics_67 = new cjs.Graphics().p("Egg6AJYIAAyvMBVQAAAIAASvg");
	var mask_1_graphics_68 = new cjs.Graphics().p("EgjHAJYIAAyvMBWRAAAIAASvg");
	var mask_1_graphics_69 = new cjs.Graphics().p("EglJAJYIAAyvMBXNAAAIAASvg");
	var mask_1_graphics_70 = new cjs.Graphics().p("Egm+AJYIAAyvMBYCAAAIAASvg");
	var mask_1_graphics_71 = new cjs.Graphics().p("EgonAJYIAAyvMBYzAAAIAASvg");
	var mask_1_graphics_72 = new cjs.Graphics().p("EgqEAJYIAAyvMBZeAAAIAASvg");
	var mask_1_graphics_73 = new cjs.Graphics().p("EgrUAJYIAAyvMBaDAAAIAASvg");
	var mask_1_graphics_74 = new cjs.Graphics().p("EgsYAJYIAAyvMBaiAAAIAASvg");
	var mask_1_graphics_75 = new cjs.Graphics().p("EgtPAJYIAAyvMBa7AAAIAASvg");
	var mask_1_graphics_76 = new cjs.Graphics().p("EgtnAJYIAAyvMBbPAAAIAASvg");
	var mask_1_graphics_77 = new cjs.Graphics().p("EgtuAJYIAAyvMBbdAAAIAASvg");
	var mask_1_graphics_78 = new cjs.Graphics().p("EgtzAJYIAAyvMBbnAAAIAASvg");
	var mask_1_graphics_79 = new cjs.Graphics().p("Egt0AJYIAAyvMBbpAAAIAASvg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:188.9,y:34.6}).wait(1).to({graphics:mask_1_graphics_1,x:188.9,y:34.6}).wait(1).to({graphics:mask_1_graphics_2,x:210,y:34.6}).wait(1).to({graphics:mask_1_graphics_3,x:221.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_4,x:233,y:34.6}).wait(1).to({graphics:mask_1_graphics_5,x:244.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_6,x:256,y:34.6}).wait(1).to({graphics:mask_1_graphics_7,x:267.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_8,x:279,y:34.6}).wait(1).to({graphics:mask_1_graphics_9,x:290.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_10,x:302,y:34.6}).wait(1).to({graphics:mask_1_graphics_11,x:313.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_12,x:325,y:34.6}).wait(1).to({graphics:mask_1_graphics_13,x:336.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_14,x:348,y:34.6}).wait(1).to({graphics:mask_1_graphics_15,x:359.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_16,x:371,y:34.6}).wait(1).to({graphics:mask_1_graphics_17,x:382.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_18,x:394,y:34.6}).wait(1).to({graphics:mask_1_graphics_19,x:405.5,y:34.6}).wait(1).to({graphics:mask_1_graphics_20,x:487.8,y:42.1}).wait(1).to({graphics:mask_1_graphics_21,x:466.4,y:41.4}).wait(1).to({graphics:mask_1_graphics_22,x:446.1,y:40.6}).wait(1).to({graphics:mask_1_graphics_23,x:427,y:39.9}).wait(1).to({graphics:mask_1_graphics_24,x:409.1,y:39.3}).wait(1).to({graphics:mask_1_graphics_25,x:392.4,y:38.7}).wait(1).to({graphics:mask_1_graphics_26,x:376.7,y:38.1}).wait(1).to({graphics:mask_1_graphics_27,x:362.3,y:37.6}).wait(1).to({graphics:mask_1_graphics_28,x:349,y:37.1}).wait(1).to({graphics:mask_1_graphics_29,x:336.9,y:36.7}).wait(1).to({graphics:mask_1_graphics_30,x:325.9,y:36.3}).wait(1).to({graphics:mask_1_graphics_31,x:316,y:36}).wait(1).to({graphics:mask_1_graphics_32,x:307.4,y:35.6}).wait(1).to({graphics:mask_1_graphics_33,x:299.9,y:35.4}).wait(1).to({graphics:mask_1_graphics_34,x:293.5,y:35.1}).wait(1).to({graphics:mask_1_graphics_35,x:288.3,y:35}).wait(1).to({graphics:mask_1_graphics_36,x:281.3,y:34.8}).wait(1).to({graphics:mask_1_graphics_37,x:274.4,y:34.7}).wait(1).to({graphics:mask_1_graphics_38,x:270.3,y:34.6}).wait(1).to({graphics:mask_1_graphics_39,x:268.9,y:34.6}).wait(1).to({graphics:mask_1_graphics_40,x:291.5,y:35}).wait(1).to({graphics:mask_1_graphics_41,x:304,y:35.4}).wait(1).to({graphics:mask_1_graphics_42,x:316.4,y:35.8}).wait(1).to({graphics:mask_1_graphics_43,x:328.9,y:36.2}).wait(1).to({graphics:mask_1_graphics_44,x:341.3,y:36.6}).wait(1).to({graphics:mask_1_graphics_45,x:353.8,y:37}).wait(1).to({graphics:mask_1_graphics_46,x:366.3,y:37.4}).wait(1).to({graphics:mask_1_graphics_47,x:378.7,y:37.8}).wait(1).to({graphics:mask_1_graphics_48,x:391.2,y:38.2}).wait(1).to({graphics:mask_1_graphics_49,x:403.6,y:38.6}).wait(1).to({graphics:mask_1_graphics_50,x:416.1,y:39}).wait(1).to({graphics:mask_1_graphics_51,x:428.6,y:39.4}).wait(1).to({graphics:mask_1_graphics_52,x:441,y:39.8}).wait(1).to({graphics:mask_1_graphics_53,x:453.5,y:40.2}).wait(1).to({graphics:mask_1_graphics_54,x:465.9,y:40.5}).wait(1).to({graphics:mask_1_graphics_55,x:478.4,y:40.9}).wait(1).to({graphics:mask_1_graphics_56,x:490.9,y:41.3}).wait(1).to({graphics:mask_1_graphics_57,x:503.3,y:41.7}).wait(1).to({graphics:mask_1_graphics_58,x:515.8,y:42.1}).wait(1).to({graphics:mask_1_graphics_59,x:420.3,y:28}).wait(1).to({graphics:mask_1_graphics_60,x:407.3,y:28.7}).wait(1).to({graphics:mask_1_graphics_61,x:395,y:29.3}).wait(1).to({graphics:mask_1_graphics_62,x:383.3,y:29.9}).wait(1).to({graphics:mask_1_graphics_63,x:372.3,y:30.4}).wait(1).to({graphics:mask_1_graphics_64,x:362,y:30.9}).wait(1).to({graphics:mask_1_graphics_65,x:352.4,y:31.4}).wait(1).to({graphics:mask_1_graphics_66,x:343.4,y:31.8}).wait(1).to({graphics:mask_1_graphics_67,x:335.1,y:32.2}).wait(1).to({graphics:mask_1_graphics_68,x:327.4,y:32.6}).wait(1).to({graphics:mask_1_graphics_69,x:320.4,y:33}).wait(1).to({graphics:mask_1_graphics_70,x:314.1,y:33.3}).wait(1).to({graphics:mask_1_graphics_71,x:308.4,y:33.6}).wait(1).to({graphics:mask_1_graphics_72,x:303.4,y:33.8}).wait(1).to({graphics:mask_1_graphics_73,x:299.1,y:34}).wait(1).to({graphics:mask_1_graphics_74,x:295.4,y:34.2}).wait(1).to({graphics:mask_1_graphics_75,x:292.5,y:34.4}).wait(1).to({graphics:mask_1_graphics_76,x:288.2,y:34.5}).wait(1).to({graphics:mask_1_graphics_77,x:284.1,y:34.6}).wait(1).to({graphics:mask_1_graphics_78,x:281.7,y:34.6}).wait(1).to({graphics:mask_1_graphics_79,x:280.9,y:34.6}).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AH6EoIAAgMQAAgLALAAQAMAAAAALIAAAMQAAAMgMAAQgLAAAAgMgAEmEuQgNgGgJgLQgKgMgEgPQgGgPAAgSQAAgTAGgPQAEgQAKgLQAJgLANgGQAOgGAPAAQAQAAANAGQANAGAJALQAKALAFAQQAFAPAAATQAAASgFAQQgFAPgJALQgJALgNAGQgNAGgRAAQgPgBgOgFgAEwCnQgJAFgGAIQgGAIgDAMQgEALAAAOQAAANAEALQACAMAHAHQAGAJAJAEQAIAFALgBQALAAAJgDQAJgFAGgIQAGgIADgLQADgLAAgOQAAgPgDgKQgDgMgGgIQgGgIgJgFQgJgDgLAAQgLAAgIADgACDEwQgPgDgKgHQgHgFAAgJIAAjNQAAgMALABQAMgBAAAMIAABKQAQgIAUAAQARAAAOAGQANAGAKALQAKALAFAPQAFAQAAARQAAATgGAQQgFAPgKALQgKAMgNAGQgOAFgQABQgNAAgOgEgACHCnIgNAHIAABnQALAGAZACQAMABAKgGQAJgFAHgKQAGgIADgLQADgKAAgNQAAgNgEgLQgDgLgHgJQgGgIgJgEQgKgDgLAAQgLAAgMADgAgeEuQgNgGgLgLQgKgLgFgQQgFgPAAgTQAAgSAGgPQAFgPAKgMQAKgLAOgGQAOgGAPAAQASAAAQAIIAAhKQAAgMAMABQALgBAAAMIAADBQAAALAIAFQAFAEAAAGQAAALgLAAQgLAAgIgMQgZAPgPAAQgQgBgOgFgAgTCnQgKAFgHAIQgHAIgDAMQgEAKAAANQAAANADAKQADALAGAIQAGAKAKAFQAKAGAMgBQANABAVgMIAAhkQgSgKgQAAQgJAAgKADgAj6EuQgOgGgJgLQgJgMgFgPQgGgPAAgSQAAgTAFgQQAGgPAJgLQAKgLANgGQAOgGAQAAQAOAAAMAFQAKADAIAIQAHAGAFAJQADAIAAAIQAAAPgHAJQgHAKgPAGQgNAGgUACQgSABgbABQACAJADAKQAEAIAFAHQAGAGAIAEQAJADAJAAQAQAAAWgIIAOgFQAKAAAAALQAAAIgMAFQgcAMgWAAQgPgBgNgFgAjvCnQgIAEgHAGQgGAHgEAKQgEAKgBANIAngCQAQgCAKgDQAKgFAFgEQAEgGAAgHQAAgIgIgIQgFgEgGgCQgIgCgIAAQgKgBgJAEgAoeEuQgNgGgJgLQgKgMgFgPQgFgPAAgSQAAgTAFgQQAFgPAKgLQAJgLANgGQAOgGAQAAQAOAAAMAFQAKADAIAIQAIAGAEAJQAEAIAAAIQAAAPgIAJQgHAKgOAGQgNAGgVACQgSABgaABQABAJAEAKQADAIAGAHQAGAGAIAEQAIADAKAAQAPAAAWgIQAMgGACABQALAAAAALQAAAIgNAFQgcAMgVAAQgQgBgNgFgAoSCnQgJAEgGAGQgHAHgEAKQgDAKgBANIAmgCQAQgCAKgDQAKgFAFgEQAFgGAAgHQAAgIgJgIQgFgEgGgCQgHgCgJAAQgKgBgIAEgAsMEwQgLgDgHgIQgGgGgEgMQgDgLAAgQIAAhdQAAgMAMAAQALAAAAAMIAABaQAAAMACAIQACAHAEAFQAFAEAIADQAHABALAAQASABATgOIAAh1QAAgMAMAAQALAAAAAMIAACLQAAALgLAAQgKAAAAgLIAAgBQgVAPgXAAQgPAAgLgEgAxJEmQgIgEAAgHQAAgFADgEQAEgCAEAAQADAAAHADQAUALAQgBQAOAAAIgEQAFgEADgDQACgGAAgGQAAgHgDgEQgDgEgHgEQgEgEgYgJQgTgIgJgJQgHgFgDgGQgDgJAAgJQAAgLAEgIQAFgIAIgGQAIgFAKgDQAJgCAKAAQARAAAVAIQAJAEAAAHQAAAMgLAAQgCgBgKgEQgMgDgMAAQgNgBgIAFQgJAFAAALQAAAGADAEQADAEAGAEIAdAMQATAJAKAIQAGAHADAGQADAIAAAKQAAAJgEAJQgEAHgHAHQgIAHgKADQgLAEgMAAQgYAAgZgOgAzBEuQgNgGgJgLQgKgMgFgPQgFgPAAgSQAAgTAFgQQAFgPAKgLQAJgLAOgGQAOgGAQAAQAOAAALAFQALADAIAIQAHAGAEAJQAEAIAAAIQAAAPgHAJQgIAKgOAGQgNAGgVACQgSABgaABQABAJAEAKQADAIAGAHQAGAGAIAEQAIADAKAAQAPAAAWgIQAMgGADABQAKAAAAALQAAAIgMAFQgdAMgVAAQgQgBgNgFgAy1CnQgJAEgGAGQgHAHgDAKQgEAKgBANIAngCQAQgCAKgDQAKgFAEgEQAFgGAAgHQAAgIgJgIQgEgEgHgCQgHgCgIAAQgKgBgJAEgAG2EqQgHgHgDgJQgCgMAAgYIAAirQAAgMALABQAMgBAAAMIAACrQAAAYADAGQAEAIALAAQALgBAAALQAAAFgDADQgDADgIAAQgTgBgHgGgAiAEmIAAiLQAAgMAMAAQALAAAAAMIAACLQAAAMgLgBQgMABAAgMgAlJEmQgpgwgagVIAABFQAAAMgMgBQgMABAAgMIAAjbQAAgMAMABQAMgBAAAMIAACBIA4g4QAGgEAEgBQAMAAAAALQAAAGgFAEIgzAxQAoAiAbAmQAEAGAAADQAAALgLAAQgGABgJgMgAp7EqQgGgHgDgJQgDgMAAgYIAAirQAAgMAMABQALgBAAAMIAACrQAAAYAEAGQADAIALAAQAMgBAAALQAAAFgDADQgEADgHAAQgTgBgIgGgAu9ExQgGAAgEgDQgEgDAAgGQAAgFADgFQAKgUBQhhIhRAAQgLAAAAgMQAAgLALAAIBeAAQAIABAEADQAFADAAAHQAAAGgGAHQgGALgmAvQgTAVgZAjIBYAAQAMgBAAALQAAALgMAAgA0PEmQgpgwgbgVIAABFQAAAMgLgBQgMABAAgMIAAjbQAAgMAMABQALgBAAAMIAACBIA5g4QAFgEAFgBQALAAAAALQAAAGgEAEIgzAxQAnAiAcAmQAEAGAAADQAAALgLAAQgGABgJgMgAH6DyIAAiXQAAgMALAAQAMAAAAAMIAACXQAAAMgMABQgLgBAAgMgArhBtIAAgMQAAgMALAAQAMAAAAAMIAAAMQAAAMgMAAQgLAAAAgMgAsOBtIAAgMQAAgMAMAAQALAAAAAMIAAAMQAAAMgLAAQgMAAAAgMgAFRBrIACgIIAIgWQADgJAIAAQALAAAAALIgCAIIgIAWQgEAJgHAAQgLAAAAgLgAElBrIACgIIAJgWQADgJAIAAQALAAAAALIgCAIIgIAWQgEAJgIAAQgLAAAAgLgAiABmIAAgNQAAgLAMAAQALAAAAALIAAANQAAAMgLgBQgMABAAgMgAoiBnQAAgIAIgDIA0gXIAIgCQAMAAAAALQAAAIgIADIg0AXIgIABQgMABAAgLgAzEBnQAAgIAIgDIAzgXIAIgCQAMAAAAALQAAAIgIADIg0AXIgIABQgLABAAgLgAU2hBQgKgBgIgHQgIgHgFgMQgFgNAAgUIAAhPIgOAAQgMAAAAgMQAAgLAMAAIAOAAIAAglQAAgLAMAAQALAAAAALIAAAlIApAAQAMAAAAALQAAAMgMAAIgpAAIAABPQAAANADAJQADAHAFAEQAIAIAOAAQAGgBAHgCIAKgDQAKAAAAAMQAAAIgMAEQgJADgKAAQgNAAgJgCgASLhEQgNgGgJgLQgKgMgFgOQgFgQAAgSQAAgTAFgQQAFgPAKgLQAJgLANgGQANgGAQAAQAQAAANAGQANAGAJALQAJALAGAPQAFAQAAATQAAATgFAQQgFAOgJAMQgKAKgMAGQgOAGgQgBQgQAAgNgFgASUjKQgIAEgGAIQgGAIgEALQgDAMAAAOQAAAOADALQADAKAHAIQAGAJAIAEQAJAEALABQALAAAJgFQAIgEAGgIQAHgIADgLQADgLAAgOQAAgOgDgMQgEgLgGgIQgGgIgIgEQgJgFgLAAQgLAAgJAFgALnhCQgLgDgGgHQgHgHgDgLQgEgMAAgQIAAheQAAgKAMgBQAMABAAAKIAABbQAAAMACAIQABAHAFAFQAEAFAIACQAHACALAAQASgBATgOIAAh1QAAgKAMgBQALABAAAKIAACNQAAALgKgBQgLABAAgLIAAgCQgVAOgWAAQgQAAgLgDgACMhBQgLgDgIgGQgIgHgFgJQgFgJAAgNQAAgMAFgLQAFgJAKgHQAKgIAQgDQARgEAWAAIAMAAIAAgNQAAgNgJgHQgJgIgPAAQgQAAgMAFIgRAFQgKAAAAgKQAAgHALgGQAIgDALgDQANgDAMAAQANAAAKADQALADAHAHQAHAHAEAJQAEAKAAALIAABNQAAAKAHAGQAGAEAAAHQAAALgMgBQgFAAgFgDQgFgDgEgFQgHAGgKAEQgNADgOAAQgLAAgKgCgACfiOQgLACgIAFQgGAEgEAGQgDAGAAAHQAAANALAIQAJAGAPABQAMgBAKgDQAKgDAGgFIAAgxIgMAAQgQABgNACgAlOhBQgLgDgIgGQgIgHgEgJQgFgJAAgNQAAgMAEgLQAFgJALgHQAKgIAQgDQAQgEAXAAIALAAIAAgNQAAgNgJgHQgJgIgPAAQgPAAgNAFIgQAFQgLAAAAgKQAAgHALgGQAJgDAKgDQANgDAMAAQANAAALADQAKADAHAHQAIAHADAJQAEAKAAALIAABNQAAAKAHAGQAGAEAAAHQAAALgLgBQgGAAgFgDQgFgDgDgFQgIAGgKAEQgMADgOAAQgMAAgKgCgAk6iOQgMACgHAFQgHAEgDAGQgDAGAAAHQAAANAKAIQAJAGAPABQANgBAKgDQAKgDAFgFIAAgxIgLAAQgRABgMACgAtBhEQgOgGgKgLQgKgMgFgPQgGgQAAgSQAAgSAGgQQAFgOALgMQAKgLAOgGQAOgGARAAQASAAAPAJIAAhLQAAgMAMAAQAMAAAAAMIAADBQAAAKAHAGQAGAEAAAHQAAALgLgBQgMABgIgMQgYANgRAAQgRAAgNgFgAs3jKQgJAEgHAIQgHAIgEALQgEALAAANQAAAMADALQADALAGAJQAHAJAJAFQAKAFANABQAOgBAVgLIAAhlQgSgJgPgBQgMAAgKAFgAx7hEQgNgGgKgLQgJgMgFgOQgGgQAAgSQAAgTAGgQQAFgPAJgLQAKgLANgGQANgGAQAAQAPAAANAGQANAGAKALQAJALAFAPQAFAQAAATQAAATgEAQQgFAOgKAMQgJAKgNAGQgNAGgQgBQgQAAgNgFgAxyjKQgIAEgHAIQgGAIgDALQgEAMAAAOQAAAOAEALQADAKAGAIQAGAJAJAEQAJAEALABQALAAAJgFQAIgEAGgIQAGgIADgLQADgLAAgOQAAgOgDgMQgDgLgGgIQgGgIgJgEQgJgFgKAAQgLAAgJAFgAQqhMIAAhaQAAgMgCgHQgCgJgEgFQgFgDgHgCQgHgDgLAAQgKAAgKADQgKACgHAEQADANAAAQIAABdQAAALgLAAQgMAAAAgLIAAhaQAAgMgBgHQgCgJgFgFQgEgDgHgCQgHgDgLAAQgMAAgLAFIgLAFIAAB5QAAALgMAAQgMAAAAgLIAAiMQAAgLALAAQALAAAAAKQATgMAWAAQAPAAALADQAKAEAHAHQALgGANgEQANgEAOAAQAPAAAKADQALADAHAIQAHAHADALQAEAMAAAQIAABdQAAALgMAAQgMAAAAgLgAKHhMIAAhaQAAgMgCgHQgCgJgEgFQgFgDgHgCQgHgDgLAAQgLAAgKADQgJACgHAEQADANAAAQIAABdQAAALgLAAQgMAAAAgLIAAhaQAAgMgCgHQgCgJgEgFQgEgDgIgCQgGgDgLAAQgMAAgLAFIgMAFIAAB5QAAALgLAAQgMAAAAgLIAAiMQAAgLALAAQALAAAAAKQATgMAWAAQAPAAALADQAKAEAHAHQALgGAMgEQAOgEAOAAQAPAAAKADQALADAHAIQAHAHADALQADAMAAAQIAABdQAAALgLAAQgMAAAAgLgAGIhMIAAiMQAAgKAMgBQAMABAAAKIAACMQAAALgMAAQgMAAAAgLgAFchJQgQgbgXggIgrA7QgGAJgGgBQgLABAAgLQAAgFAEgFIAvhDQgcgkgRgSQgFgEAAgGQAAgLAMAAQAFAAAEAFQAMALAfAoIAjgwQAGgHAGgBQALAAAAALQAAAFgFAHIgmA0QASAZAbAqQADAGAAAEQAAAKgLAAQgHABgFgJgAAxhMIAAhaQAAgMgCgHQgCgJgFgFQgEgDgIgCQgGgDgLAAQgLAAgIADQgJACgIAEQAEANAAAQIAABdQAAALgMAAQgLAAAAgLIAAhaQAAgMgCgHQgCgJgEgFQgFgDgHgCQgHgDgLAAQgMAAgKAFIgMAFIAAB5QAAALgMAAQgLAAAAgLIAAiMQAAgLALAAQAKAAAAAKQATgMAWAAQAQAAAKADQALAEAGAHQAMgGAMgEQAMgEAOAAQAOAAALADQALADAGAIQAHAHAEALQADAMAAAQIAABdQAAALgMAAQgLAAAAgLgAnvhMIAAiMQAAgKAMgBQALABAAAKIAACMQAAALgLAAQgMAAAAgLgAoehMQgogwgbgVIAABFQAAALgMAAQgLAAAAgLIAAjbQAAgMALAAQAMAAAAAMIAACCIA5g4QAFgGAFAAQALAAAAALQAAAGgFAEIgyAyQAnAhAbAnQAEAFAAAEQAAALgLgBQgFAAgKgLgAv1hBQgGAAgEgCQgEgDAAgHQAAgGADgEQAKgTBQhiIhRAAQgLAAAAgMQAAgLALAAIBeAAQAIAAAEADQAFAEAAAHQAAAHgGAGQgGALgmAuQgTAWgZAjIBYAAQAMAAAAALQAAALgMgBgAzjhMIAAhgIhpAAIAABgQAAALgMAAQgLAAAAgLIAAjLQAAgMALAAQAMAAAAAMIAABVIBpAAIAAhVQAAgMAMAAQALAAAAAMIAADLQAAALgLAAQgMAAAAgLgAGIkNIAAgMQAAgLAMAAQAMAAAAALIAAAMQAAAMgMABQgMgBAAgMgAnvkNIAAgMQAAgLAMAAQALAAAAALIAAAMQAAAMgLABQgMgBAAgMg");
	this.shape.setTransform(138.8,12.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AdNEDIAAgKQAAgKAKAAQAKAAAAAKIAAAKQAAAKgKAAQgKAAAAgKgAZNECQgHgEAAgHQAAgEADgDQACgCAEAAQADgBAGAEQARAIAPAAQAMAAAHgDQAEgDACgEQADgFAAgFQAAgGgDgDQgDgFgGgCQgDgEgVgHQgRgIgIgHQgGgFgCgGQgEgGAAgJQAAgJAFgIQAEgHAHgEQAHgFAIgDQAJgCAIAAQAPAAASAIQAIADAAAGQAAAKgJAAIgLgDQgLgEgKAAQgLAAgHAEQgJAEAAAKQAAAFAEAEQACADAGAEIAZAKQARAIAIAIQAFAFADAGQADAHAAAIQAAAIgEAHQgDAHgHAHQgGAFgJADQgKADgKAAQgVAAgWgLgAYOELQgJgCgHgFQgHgGgEgLQgFgMAAgQIAAhGIgMAAQgKAAAAgKQAAgKAKAAIAMAAIAAggQAAgKALAAQAKAAAAAKIAAAgIAkAAQAKAAAAAKQAAAKgKAAIgkAAIAABGQAAALACAHQADAHAEADQAHAHANgBQAFAAAGgBIAJgCQAIgBAAAKQAAAIgKAEQgIACgJAAQgLAAgIgCgAWAEIQgLgFgIgKQgJgJgEgOQgFgOAAgQQAAgQAFgNQAEgOAJgKQAIgKALgEQANgGAOAAQAMAAAKAEQAJAEAHAGQAHAGADAHQAEAIAAAHQAAANgHAIQgGAJgNAEQgLAFgSACQgQACgXAAQABAJADAHQADAHAFAHQAGAFAHADQAHADAIAAQAOAAATgHIAMgEQAKAAAAAKQAAAGgLAFQgZAKgTAAQgNAAgMgFgAWKCSQgHADgGAGQgGAGgDAJQgDAJgBAKIAigBQAOgCAJgDQAIgDAFgEQAEgFAAgGQAAgIgIgHQgEgDgGgCQgGgCgHAAQgJAAgIADgAPnEIQgMgFgIgKQgIgJgEgOQgFgOAAgQQAAgQAEgNQAFgOAIgKQAJgKALgEQANgGAOAAQAMAAAKAEQAJAEAHAGQAGAGAEAHQADAIAAAHQAAANgGAIQgGAJgNAEQgLAFgSACQgQACgXAAQABAJADAHQADAHAFAHQAFAFAHADQAIADAIAAQANAAAUgHIAMgEQAJAAAAAKQAAAGgKAFQgZAKgTAAQgNAAgMgFgAPxCSQgHADgGAGQgGAGgDAJQgDAJgBAKIAigBQAOgCAJgDQAIgDAFgEQADgFAAgGQAAgIgHgHQgEgDgGgCQgGgCgHAAQgJAAgIADgAOLELQgKgCgHgFQgHgGgEgLQgFgMAAgQIAAhGIgMAAQgKAAAAgKQAAgKAKAAIAMAAIAAggQAAgKALAAQAKAAAAAKIAAAgIAkAAQALAAAAAKQAAAKgLAAIgkAAIAABGQAAALACAHQADAHAEADQAHAHANgBQAFAAAGgBIAJgCQAJgBAAAKQAAAIgLAEQgIACgJAAQgLAAgHgCgAL8EIQgLgFgIgKQgJgJgEgOQgFgOAAgQQAAgQAFgNQAEgOAJgKQAIgKAMgEQAMgGAOAAQAMAAAKAEQAKAEAHAGQAGAGAEAHQADAIAAAHQAAANgGAIQgHAJgMAEQgMAFgSACQgPACgYAAQABAJAEAHQADAHAFAHQAFAFAHADQAHADAJAAQANAAATgHIANgEQAJAAAAAKQAAAGgLAFQgZAKgSAAQgOAAgMgFgAMHCSQgIADgFAGQgGAGgDAJQgEAJgBAKIAigBQAOgCAJgDQAJgDAEgEQAEgFAAgGQAAgIgHgHQgFgDgFgCQgHgCgHAAQgJAAgHADgAEREIQgLgFgIgKQgJgJgEgOQgFgOAAgQQAAgPAFgOQAEgOAJgKQAIgKALgEQAMgGAOAAQANAAAMAGQALAEAIAKQAIAKAFAOQAFAOAAAPQAAARgFAOQgEANgIAJQgIAKgLAGQgMAEgOAAQgOAAgMgFgAEZCTQgHADgFAIQgGAGgDALQgDAJAAAMQAAAMADAKQADAKAGAHQAFAHAHAEQAIADAKAAQAJAAAIgDQAHgEAGgHQAFgHADgJQADgLAAgMQAAgMgDgJQgDgLgFgGQgGgIgHgDQgIgEgJAAQgKAAgIAEgAC1ELQgJgCgHgFQgHgGgFgLQgEgMAAgQIAAhGIgMAAQgLAAAAgKQAAgKALAAIAMAAIAAggQAAgKAKAAQAKAAAAAKIAAAgIAlAAQAKAAAAAKQAAAKgKAAIglAAIAABGQAAALADAHQACAHAFADQAHAHANgBQAEAAAHgBIAIgCQAJgBAAAKQAAAIgLAEQgHACgJAAQgLAAgIgCgAAlELQgJgCgHgGQgHgFgEgJQgFgJAAgLQAAgKAFgJQAEgJAJgFQAJgHAOgDQAOgDAUgBIAKAAIAAgKQAAgMgIgGQgIgHgNAAQgOAAgLAEIgOAFQgJAAAAgJQAAgHAJgEQAIgEAJgCQALgDALAAQALAAAKADQAJADAGAGQAGAGADAIQAEAIAAALIAABDQAAAJAGAEQAGAEAAAGQAAAKgLgBQgFAAgEgCQgEgEgDgEQgHAFgJAEQgLADgMAAQgKAAgJgCgAA2DHQgJADgHADQgGAEgDAFQgDAGAAAFQAAAMAJAHQAIAFANAAQAMAAAIgCQAJgDAFgFIAAgqIgKAAQgPAAgLACgAjlEIQgLgFgIgKQgJgJgEgOQgFgOAAgQQAAgPAFgOQAEgOAJgKQAIgKALgEQAMgGAOAAQANAAAMAGQALAEAIAKQAIAKAFAOQAFAOAAAPQAAARgFAOQgEANgIAJQgIAKgLAGQgMAEgOAAQgOAAgMgFgAjdCTQgHADgFAIQgGAGgDALQgDAJAAAMQAAAMADAKQADAKAGAHQAFAHAHAEQAIADAKAAQAJAAAIgDQAHgEAGgHQAFgHADgJQADgLAAgMQAAgMgDgJQgDgLgFgGQgGgIgHgDQgIgEgJAAQgKAAgIAEgAmtELQgKgCgHgGQgHgFgDgJQgFgJAAgLQAAgKAEgJQAEgJAKgFQAIgHAOgDQAPgDAUgBIAJAAIAAgKQAAgMgHgGQgIgHgNAAQgOAAgLAEIgOAFQgKAAAAgJQAAgHAKgEQAIgEAJgCQALgDALAAQALAAAJADQAJADAHAGQAGAGADAIQAEAIAAALIAABDQAAAJAGAEQAFAEAAAGQAAAKgKgBQgFAAgEgCQgFgEgDgEQgGAFgJAEQgLADgMAAQgKAAgJgCgAmcDHQgKADgGADQgGAEgDAFQgDAGAAAFQAAAMAJAHQAIAFANAAQALAAAJgCQAJgDAEgFIAAgqIgJAAQgPAAgLACgAsGELQgJgEgGgGQgGgGgDgKQgCgKAAgOIAAhSQAAgKAKAAQAKAAAAAKIAABPQAAAKACAIQABAGAEAEQAEAEAHACQAGABAKAAQAPABARgMIAAhnQAAgKAKAAQAKAAAAAKIAAB7QAAAKgJgBQgKABAAgKIAAgCQgSANgTAAQgOAAgKgCgAwJELQgKgCgHgGQgHgFgEgJQgEgJAAgLQAAgKAEgJQAEgJAJgFQAJgHAOgDQAPgDATgBIAKAAIAAgKQAAgMgHgGQgIgHgNAAQgOAAgLAEIgOAFQgKAAAAgJQAAgHAKgEQAHgEAKgCQALgDALAAQALAAAJADQAJADAHAGQAGAGADAIQAEAIAAALIAABDQAAAJAGAEQAFAEAAAGQAAAKgKgBQgFAAgEgCQgFgEgDgEQgGAFgJAEQgLADgMAAQgKAAgJgCgAv4DHQgKADgHADQgFAEgDAFQgDAGAAAFQAAAMAJAHQAIAFANAAQALAAAJgCQAJgDAEgFIAAgqIgKAAQgOAAgLACgAyYECQgHgEAAgHQAAgEADgDQADgCAEAAQADgBAGAEQARAIAOAAQANAAAHgDQAEgDACgEQADgFAAgFQAAgGgDgDQgDgFgGgCQgEgEgUgHQgRgIgIgHQgGgFgDgGQgDgGAAgJQAAgJAEgIQAFgHAHgEQAGgFAJgDQAIgCAJAAQAPAAASAIQAIADAAAGQAAAKgJAAIgLgDQgLgEgKAAQgLAAgHAEQgJAEAAAKQAAAFADAEQADADAFAEIAZAKQARAIAJAIQAFAFADAGQADAHAAAIQAAAIgEAHQgDAHgHAHQgHAFgJADQgJADgLAAQgUAAgXgLgA0NECQgHgEAAgHQAAgEADgDQADgCADAAQADgBAGAEQARAIAPAAQAMAAAHgDQAFgDACgEQACgFAAgFQAAgGgDgDQgDgFgFgCQgEgEgVgHQgRgIgIgHQgFgFgDgGQgDgGAAgJQAAgJAEgIQAEgHAHgEQAHgFAIgDQAJgCAJAAQAOAAATAIQAHADAAAGQAAAKgJAAIgLgDQgLgEgJAAQgMAAgHAEQgIAEAAAKQAAAFADAEQACADAGAEIAZAKQARAIAIAIQAFAFADAGQADAHAAAIQAAAIgEAHQgDAHgHAHQgGAFgJADQgJADgLAAQgVAAgWgLgA12EIQgLgFgJgKQgIgJgEgOQgFgOAAgQQAAgQAFgNQAEgOAIgKQAJgKALgEQANgGAOAAQAMAAAKAEQAJAEAHAGQAGAGAEAHQADAIAAAHQAAANgGAIQgGAJgNAEQgLAFgSACQgQACgXAAQABAJADAHQADAHAFAHQAGAFAHADQAHADAIAAQAOAAATgHIAMgEQAKAAAAAKQAAAGgLAFQgZAKgTAAQgNAAgMgFgA1sCSQgHADgGAGQgGAGgDAJQgDAJgBAKIAigBQAOgCAJgDQAIgDAFgEQADgFAAgGQAAgIgHgHQgEgDgGgCQgGgCgHAAQgJAAgIADgA49EIQgLgFgIgKQgJgJgEgOQgFgOAAgQQAAgQAFgNQAEgOAJgKQAIgKAMgEQAMgGAOAAQAMAAAKAEQAJAEAHAGQAHAGAEAHQADAIAAAHQAAANgHAIQgGAJgNAEQgLAFgSACQgQACgXAAQABAJADAHIAIAOQAGAFAHADQAHADAIAAQAOAAATgHIANgEQAJAAAAAKQAAAGgLAFQgZAKgTAAQgNAAgMgFgA4zCSQgHADgGAGQgFAGgEAJQgDAJgBAKIAigBQAOgCAJgDQAJgDAEgEQAEgFAAgGQAAgIgIgHQgEgDgFgCQgHgCgHAAQgJAAgIADgA9TECQgHgEAAgHQAAgEADgDQADgCADAAQAEgBAFAEQASAIAOAAQANAAAHgDQAEgDACgEQACgFAAgFQAAgGgDgDQgDgFgFgCQgEgEgVgHQgRgIgHgHQgGgFgDgGQgDgGAAgJQAAgJAEgIQAEgHAHgEQAHgFAJgDQAIgCAJAAQAOAAATAIQAIADAAAGQAAAKgKAAIgLgDQgKgEgKAAQgMAAgHAEQgIAEAAAKQAAAFADAEQADADAFAEIAZAKQARAIAIAIQAFAFADAGQADAHAAAIQAAAIgDAHQgEAHgGAHQgHAFgJADQgJADgLAAQgVAAgWgLgAbHELQgFAAgDgCQgEgDAAgGQAAgEADgEQAIgRBHhWIhHAAQgLAAAAgKQAAgKALAAIBSAAQAHABADACQAEAEAAAFQAAAGgEAGQgGAJgiApQgQATgWAeIBNAAQAKAAAAAKQAAAKgKgBgAUrECIAAhQQAAgKgBgHQgCgHgEgEQgEgEgGgCQgHgBgKAAQgKAAgLAEIgLAEIAABrQAAAKgKgBQgKABAAgKIAAjAQAAgLAKAAQAKAAAAALIAABDQAHgEAHgDQALgDALAAQAPAAALAEQAJADAGAIQAFAGADAKQACAKAAANIAABRQAAAKgKgBQgLABAAgKgARVELQgGAAgDgCQgDgDAAgGQAAgEACgEQAIgRBHhWIhHAAQgKAAAAgKQAAgKAKAAIBSAAQAHABAEACQAEAEAAAFQAAAGgFAGQgGAJghApQgQATgWAeIBNAAQAKAAAAAKQAAAKgKgBgAKoECIAAhQQAAgKgCgHQgCgHgEgEQgDgEgHgCQgGgBgLAAQgJAAgLAEIgLAEIAABrQAAAKgLgBQgKABAAgKIAAh7QAAgKAKAAQAJAAAAAJQASgLAUAAQANAAAKADQAKADAGAGQAFAHADAKQADAJAAAPIAABSQAAAKgKgBQgKABAAgKgAHbECIAAhQQAAgKgCgHQgCgHgEgEQgEgEgGgCQgGgBgLAAQgJAAgLAEIgLAEIAABrQAAAKgLgBQgKABAAgKIAAh7QAAgKAKAAQAJAAAAAJQASgLAUAAQANAAAKADQAJADAGAGQAGAHADAKQADAJAAAPIAABSQAAAKgKgBQgKABAAgKgAhvELQgGAAgDgCQgDgDAAgGQAAgEADgEQAIgRBGhWIhHAAQgKAAAAgKQAAgKAKAAIBTAAQAHABADACQAEAEAAAFQAAAGgFAGQgGAJghApQgQATgWAeIBNAAQAKAAAAAKQAAAKgKgBgAk2EEQgFgGgDgIQgCgKAAgVIAAiVQAAgLAKAAQAKAAAAALIAACVQAAAVADAGQADAGAKAAQAKAAAAAKQAAAEgDADQgDACgHAAQgQgBgHgGgAn9ECIAAhQQAAgKgBgHQgCgHgEgEQgEgEgGgCQgHgBgKAAQgKAAgLAEIgLAEIAABrQAAAKgKgBQgKABAAgKIAAjAQAAgLAKAAQAKAAAAALIAABDQAHgEAHgDQALgDALAAQAPAAALAEQAJADAGAIQAFAGADAKQACAKAAANIAABRQAAAKgKgBQgLABAAgKgAuAEDQgMgZgihdIgBgGQAAgKAKAAQAHAAADAIQAbBMAPAkQAQgkAbhMQACgIAIAAQAJABAAAIIgBAHQgiBdgMAZQgFAJgKgBQgJABgGgJgA3HEEQgGgGgCgIQgDgKAAgVIAAiVQAAgLALAAQAKAAAAALIAACVQAAAVACAGQAEAGAJAAQALAAAAAKQAAAEgDADQgDACgHAAQgQgBgHgGgA7YELQgGAAgDgCQgDgDAAgGQAAgEACgEQAIgRBHhWIhHAAQgKAAAAgKQAAgKAKAAIBSAAQAHABAEACQAEAEAAAFQAAAGgFAGQgGAJghApQgQATgWAeIBNAAQAKAAAAAKQAAAKgKgBgAdNDUIAAiFQAAgKAKAAQAKAAAAAKIAACFQAAAKgKAAQgKAAAAgKgAjiBZQAAgGAGgDIAtgUIAHgBQAKgBAAALQAAAGgHADIgtATIgHACQgJAAAAgKgAm0BZQAAgGAHgDIAtgUIAHgBQAKgBAAALQAAAGgHADIgtATIgHACQgKAAAAgKgAsNBZQAAgGAHgDIAtgUIAHgBQAKgBAAALQAAAGgHADIgtATIgHACQgKAAAAgKgAwQBZQAAgGAGgDIAugUIAHgBQAKgBAAALQAAAGgHADIgtATIgHACQgKAAAAgKgA5ABZQAAgGAHgDIAtgUIAHgBQAKgBAAALQAAAGgHADIgtATIgHACQgKAAAAgKgAhwACQgJgCAAgHQAAgJAJAAQAJADAGAAQALAAAIgJQAFgFAFgJQAGgKAFgPQgTgbgiheIgBgHQAAgJALAAQAHAAACAHQAdBSAOAZIAnhrQADgHAGAAQAJAAAAAJIgCAIIgpB1QgHATgHAOQgHAOgIAIQgHAIgJABQgIAEgKAAQgIAAgHgCgAjrgCQgHgDAAgHQAAgKAKAAIAGACQAOAHAOAAQAJgBAIgCQAJgCAGgEQAIgFAEgJQAFgJAAgMIAAgHQgRAKgPgBQgPAAgMgEQgLgFgJgKQgIgKgEgOQgFgNAAgRQAAgQAFgNQAEgNAJgKQAJgKAMgFQANgFAOAAQAOAAANAEQALADAGAEQAGAFAAAJIAAByQAAAOgGAUQgGAMgLAIQgJAHgNABQgLADgNAAQgZgCgMgEgAjFixQgJAFgGAHQgGAGgDAKQgDAJAAAMQAAAMADAKQADALAGAGQAFAIAIADQAIAEAKAAQAJAAAKgEQAKgEADgDIAAhYQgQgIgOAAQgKAAgIAEgAqKgCQgIgDAAgHQAAgKAKAAIAGACQAOAHAOAAQAJgBAIgCQAJgCAHgEQAHgFAFgJQAEgJAAgMIAAgHQgQAKgQgBQgOAAgMgEQgMgFgIgKQgJgKgEgOQgFgNAAgRQAAgQAFgNQAFgNAIgKQAJgKAMgFQANgFAOAAQAOAAANAEQALADAGAEQAGAFAAAJIAAByQAAAOgGAUQgGAMgLAIQgJAHgNABQgLADgNAAQgZgCgLgEgAplixQgJAFgGAHQgGAGgDAKQgDAJAAAMQAAAMADAKQADALAGAGQAFAIAIADQAIAEAKAAQAJAAAKgEQAKgEADgDIAAhYQgQgIgOAAQgKAAgIAEgAPag5QgJgCgHgFQgHgGgEgJQgEgIAAgLQAAgLAEgJQAEgIAJgGQAJgGAOgEQAOgDAUAAIAKAAIAAgLQAAgLgIgHQgIgGgNgBQgNAAgLAEIgPAFQgJABAAgKQAAgGAKgFQAHgEAJgCQAMgCAKAAQALAAAKADQAJADAGAFQAHAHADAIQADAHAAALIAABDQAAAJAGAFQAGAEAAAFQAAAKgKAAQgFAAgFgDQgEgDgDgFQgHAGgJADQgKADgNAAQgKAAgJgCgAPsh8QgKACgHAEQgGAEgDAFQgCAFAAAGQAAAMAJAGQAIAGANAAQALAAAJgCQAIgEAFgEIAAgqIgKAAQgPAAgKACgAMgg4QgJgCgHgGQgHgGgEgKQgFgMAAgRIAAhGIgMAAQgKABAAgLQAAgJAKAAIAMAAIAAghQAAgJAKgBQALABAAAJIAAAhIAkAAQAKAAAAAJQAAALgKgBIgkAAIAABGQAAALACAIQADAGAEAEQAHAGANAAQAFAAAGgCIAJgCQAIAAAAAJQAAAIgKAEQgIACgJAAQgLAAgIgBgAIig8QgMgEgIgKQgIgKgEgOQgFgNAAgQQAAgRAEgNQAFgOAIgJQAJgKALgFQAMgFAOAAQANAAAKADQAJAEAHAGQAGAHAEAHQADAHAAAHQAAANgGAJQgGAIgNAEQgMAGgRABQgQADgXAAQABAIADAIIAIANQAFAGAHACQAIAEAIAAQANAAATgIQALgEACAAQAJAAAAAKQAAAHgLAFQgZAJgSAAQgOABgLgGgAIsiyQgHAEgGAFQgGAGgDAJQgDAJgBALIAigCQAOgBAIgEQAJgDAEgEQAEgFAAgGQAAgIgHgGQgEgDgGgCQgGgCgIgBQgIAAgIADgAFVg5QgNgDgIgGQgHgFAAgIIAAizQAAgKAKAAQAKAAAAAKIAABCQAOgIASAAQAOAAANAFQALAFAJAJQAIALAFANQAEANAAAQQAAARgEANQgFANgJALQgIAJgMAFQgNAGgOgBQgLAAgMgCgAFZixIgMAFIAABbQAKAFAVACQALAAAJgFQAIgEAGgIQAFgIADgJQADgJAAgLQAAgMgEgKQgDgKgFgGQgGgIgIgDQgIgDgKgBQgKABgKADgADGg5QgNgDgJgGQgHgFAAgIIAAizQAAgKALAAQAKAAAAAKIAABCQAOgIASAAQAOAAAMAFQAMAFAJAJQAIALAEANQAFANAAAQQAAARgFANQgFANgJALQgIAJgMAFQgMAGgOgBQgLAAgMgCgADJixIgLAFIAABbQAKAFAVACQALAAAJgFQAIgEAFgIQAFgIADgJQADgJAAgLQAAgMgDgKQgDgKgGgGQgGgIgIgDQgIgDgJgBQgKABgLADgAA3g8QgMgEgIgKQgIgKgFgOQgEgNAAgQQAAgQAEgOQAFgOAIgJQAIgKAMgFQALgFAOAAQAOAAALAFQALAFAJAKQAIAJAEAOQAFAOAAAQQAAARgEANQgFAOgIAJQgIAKgLAFQgMAEgOAAQgOABgLgGgAA/ixQgIAEgFAHQgFAHgDAKQgDAKAAAMQAAAMADAJQACALAGAGQAFAIAIADQAHAEAKAAQAKAAAHgEQAIgDAFgIQAGgGACgKQADgKAAgMQAAgMgDgKQgDgKgFgHQgFgHgIgEQgIgDgJgBQgKABgHADgAlWg5QgJgCgHgFQgHgGgEgJQgFgIAAgLQAAgLAEgJQAFgIAJgGQAIgGAOgEQAPgDAUAAIAKAAIAAgLQAAgLgIgHQgIgGgNgBQgOAAgLAEIgOAFQgJABAAgKQAAgGAJgFQAIgEAJgCQALgCALAAQALAAAJADQAKADAGAFQAGAHADAIQAEAHAAALIAABDQAAAJAGAFQAFAEAAAFQAAAKgKAAQgFAAgEgDQgEgDgEgFQgGAGgJADQgLADgMAAQgKAAgJgCgAlFh8QgKACgGAEQgGAEgDAFQgDAFAAAGQAAAMAJAGQAIAGANAAQALAAAJgCQAJgEAFgEIAAgqIgKAAQgPAAgLACgAr0g8QgMgEgIgKQgIgKgEgOQgFgNAAgQQAAgRAEgNQAFgOAIgJQAJgKALgFQANgFAOAAQAMAAAKADQAJAEAHAGQAGAHAEAHQADAHAAAHQAAANgGAJQgGAIgNAEQgLAGgSABQgQADgXAAQABAIADAIQADAHAFAGQAFAGAHACQAIAEAIAAQANAAAUgIIAMgEQAJAAAAAKQAAAHgKAFQgZAJgTAAQgNABgMgGgArqiyQgHAEgGAFQgGAGgDAJQgDAJgBALIAigCQAOgBAJgEQAIgDAFgEQADgFAAgGQAAgIgHgGQgEgDgGgCQgGgCgHgBQgJAAgIADgAv6g5QgKgCgHgFQgHgGgDgJQgFgIAAgLQAAgLAEgJQAEgIAJgGQAJgGAOgEQAPgDAUAAIAJAAIAAgLQAAgLgHgHQgIgGgNgBQgOAAgLAEIgOAFQgKABAAgKQAAgGAKgFQAHgEAKgCQALgCALAAQALAAAJADQAJADAHAFQAGAHADAIQAEAHAAALIAABDQAAAJAGAFQAFAEAAAFQAAAKgKAAQgFAAgEgDQgFgDgDgFQgGAGgJADQgLADgMAAQgKAAgJgCgAvph8QgKACgGAEQgGAEgDAFQgDAFAAAGQAAAMAJAGQAIAGANAAQALAAAJgCQAJgEAEgEIAAgqIgJAAQgPAAgLACgA3Lg5QgJgEgGgFQgGgHgDgJQgDgLAAgOIAAhSQAAgJALAAQAKAAAAAJIAABQQAAAKABAHQACAHAEADQAEAFAHACQAGABAKAAQAPAAARgMIAAhnQAAgJAKAAQAKAAAAAJIAAB7QAAAKgJAAQgKAAAAgKIAAgBQgSANgUgBQgNAAgKgCgA6Rg8QgLgEgIgKQgJgKgEgOQgFgNAAgQQAAgRAFgNQAEgOAJgJQAIgKAMgFQAMgFAOAAQAMAAAKADQAJAEAHAGQAHAHAEAHQADAHAAAHQAAANgHAJQgGAIgNAEQgLAGgSABQgQADgXAAQABAIADAIIAIANQAGAGAHACQAHAEAIAAQAOAAATgIIANgEQAJAAAAAKQAAAHgLAFQgZAJgTAAQgNABgMgGgA6HiyQgHAEgGAFQgFAGgEAJQgDAJgBALIAigCQAOgBAJgEQAJgDAEgEQAEgFAAgGQAAgIgIgGQgEgDgFgCQgHgCgHgBQgJAAgIADgANhhCIAAh7QAAgJAKAAQAKAAAAAJIAAAMQADgHAJgIIALgGQAHgCAHAAIANABQAKADAAAHQAAALgKgBQgHgCgGAAQgPACgHAIQgHAIgEAKQgEAOAAASIAAA3QAAAKgKAAQgKAAAAgKgALWhAQgNgXgVgdIglA0QgFAIgGAAQgKAAAAgKQAAgEAEgEIApg7QgZgfgOgQQgFgEAAgFQAAgJALAAQAEAAAEADQAKALAcAjIAegqQAFgHAGAAQAJAAAAAJQAAAEgEAHIgiAtQAQAWAXAlQAEAEAAAFQAAAJgLAAQgFAAgFgIgAmlhCIAAhPQAAgKgCgHQgCgIgEgDQgEgEgGgCQgHgBgKgBQgKABgKADIgMAFIAABqQAAAKgKAAQgKAAAAgKIAAh7QAAgJAKAAQAJAAAAAIQASgKAUAAQANAAAKADQAJACAGAHQAGAGADAKQADALAAAOIAABRQAAAKgKAAQgKAAAAgKgAtFhAQgGgFgCgJQgDgJAAgWIAAiVQAAgKAKAAQALAAAAAKIAACVQAAAWACAFQAEAGAJABQAKAAAAAJQAAAFgCACQgDADgHAAQgRgCgGgGgAx3hCQgkgrgXgSIAAA9QAAAKgKAAQgLAAAAgKIAAjAQAAgKALAAQAKAAAAAKIAABxIAxgwQAFgFAEAAQAKAAAAAJQAAAFgEAEIgsAsQAiAdAYAhQAEAFAAADQAAAKgKAAQgFAAgIgKgA0AhCIAAhPQAAgKgBgHQgCgIgEgDQgEgEgGgCQgHgBgKgBQgKABgKADIgMAFIAABqQAAAKgKAAQgKAAAAgKIAAh7QAAgJAJAAQAKAAAAAIQASgKAUAAQANAAAJADQAKACAGAHQAGAGADAKQADALAAAOIAABRQAAAKgKAAQgLAAAAgKgA4bhAQgGgFgCgJQgDgJAAgWIAAiVQAAgKALAAQAKAAAAAKIAACVQAAAWACAFQAEAGAJABQALAAAAAJQAAAFgDACQgDADgHAAQgQgCgHgGgA8bg7QgEgCgCgFQgSgngsiEIgBgHQAAgKAJAAQAHAAADAHQAqCCASAnQASgnAqiCQADgHAHAAQAKAAAAAKIgCAHQgsCEgSAnQgCAFgEACQgEADgGAAQgGAAgEgDgARXh3QgKAAAAgKQAAgJAKAAIBFAAQAKAAAAAJQAAAKgKAAgA2ljkIAAgKQAAgLAKAAQAKAAAAALIAAAKQAAAKgKAAQgKAAAAgKgA3MjkIAAgKQAAgLAKAAQAKAAAAALIAAAKQAAAKgKAAQgKAAAAgKg");
	this.shape_1.setTransform(189,10.6);

	this.shape.mask = this.shape_1.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},20).to({state:[{t:this.shape}]},39).wait(21));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-18.2,277.6,61.6);


(lib.erdekelBtn = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AgOgnIAdAnIgdAo");
	this.shape.setTransform(106.5,13.4);

	// Érdekel
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACMBHQgGgDgFgGQgEgFgDgHQgCgIAAgIQAAgKACgHQADgIAEgFQAFgEAGgCQAHgDAIAAQAHAAAFACQAFACAEABQAEAEACAEQACAEAAAEQAAAHgEAEQgDAFgHADQgHADgKAAIgVACQAAAEACAEQACAFADADIAGAFQAEABAFAAQAIABAKgEIAHgDQAFAAAAAGQAAADgGADQgOAGgKgBQgHAAgHgCgACSAGQgEABgDADIgFAIQgCAFgBAGIATgBIANgCQAFgBACgEQACgCAAgDQAAgFgEgDQgCgCgEgBIgHgBQgFAAgEACgAAABHQgEgDgFgGQgEgFgDgHQgCgIAAgIQAAgKACgHQADgIAEgFQAFgEAEgCQAHgDAIAAQAHAAAFACQAFACAEABQAEAEACAEQACAEAAAEQAAAHgEAEQgDAFgHADQgHADgKAAIgTACQAAAEACAEQACAFACADIAFAFQAEABAFAAQAIABAKgEIAHgDQAFAAAAAGQAAADgGADQgOAGgKgBQgHAAgHgCgAAGAGQgEABgCADIgEAIQgCAFgBAGIARgBIANgCQAFgBACgEQACgCAAgDQAAgFgEgDQgCgCgEgBIgHgBQgFAAgEACgAhMBHQgGgDgFgGQgFgFgDgHQgCgIAAgJQAAgIACgIQADgIAFgFQAFgEAHgCQAGgDAJAAQAIAAAIAEIAAgkQAAgFAGgBQAFABAAAFIAABbQAAAFAEADQADACAAADQAAAFgGAAQgGABgDgHQgMAIgIgBQgIAAgHgCgAhHAGQgEACgEAEQgDADgCAGQgCAFAAAHQAAAGACAFQABAFADAEQADAFAFACQAFACAGAAQAHAAAKgFIAAgxQgJgEgHAAQgGAAgFACgADNBFQgDgEgCgEQgBgGAAgLIAAhRQAAgFAGgBQAFABAAAFIAABRQAAALACAEQABADAGAAQAFAAAAAFQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgCACgEgBQgIAAgEgDgABnBDQgUgXgNgKIAAAhQAAAFgFAAQgGAAAAgFIAAhoQAAgFAGgBQAFABAAAFIAAA9IAcgZQACgDACAAQAGAAAAAEQAAAAAAABQgBAAAAABQAAAAAAABQgBABAAAAIgZAYQATARANARQABABAAABQABAAAAABQAAAAAAABQAAABAAAAQAAAFgFAAQgDAAgEgFgAiTBDIAAhDQAAgEAGAAQAGAAAAAEIAAAGQABgEAFgCIAHgEIAHgBIAHAAQAGACAAADQAAAFgGAAIgHgBQgIABgEAEQgEAEgCAGQgCAIAAAKIAAAeQAAAFgGAAQgGAAAAgFgAjXBIQgIAAAAgHIAAhcQAAgIAIAAIAqAAQAFAAAAAGQAAAFgFAAIgnAAIAAAhIAkAAQAGABAAAFQAAAGgGgBIgkAAIAAAqIAqAAQAGAAAAAFQAAAFgGAAgAjWg3QAAgEAEgCIAZgKIAEgBQAFgBAAAGQAAADgDACIgZALIgEABQgGAAAAgFg");
	this.shape_1.setTransform(56.5,11.7);

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.098)").s().p("ApTBUIAAigQAAgsAsAAIRWAAQAbAAAKAQQgKgGgRAAIxWAAQgsAAAAAsIAACgQAAARAGAKQgQgKAAgbg");
	this.shape_2.setTransform(59.7,12.2);

	// Layer 3
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF7D00").s().p("AoqB9QgsgBgBgrIAAigQABgsAsgBIRVAAQAtABgBAsIAACgQABArgtABg");
	this.shape_3.setTransform(60,12.5);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,120,25);


(lib.Tween144 = function() {
	this.initialize();

	// Layer 1
	this.erdekelBtn = new lib.erdekelBtn();
	this.erdekelBtn.setTransform(-6,6,1,1,0,0,0,60,13.5);

	this.addChild(this.erdekelBtn);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66,-7.5,120,25);


(lib.Symbol444 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_15 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(9).call(this.frame_9).wait(6).call(this.frame_15).wait(1));

	// Layer 2
	this.instance = new lib.Tween3244("synched",0);
	this.instance.setTransform(271.1,343.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-293,y:345.6},9,cjs.Ease.get(1)).to({x:277.1,y:343.6},6).wait(1));

	// Layer 3
	this.instance_1 = new lib.Tween3344("synched",0);
	this.instance_1.setTransform(281.3,-96.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-282.8},9,cjs.Ease.get(1)).to({x:287.3},6).wait(1));

	// Layer 1
	this.instance_2 = new lib.Tween3444("synched",0);
	this.instance_2.setTransform(10.5,-43.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:-89.5,y:5.5},9,cjs.Ease.get(1)).to({x:10.5,y:-43.5},6).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-230.3,625.4,811.1);


(lib.p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_111 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(111).call(this.frame_111).wait(26));

	// Layer 3
	this.instance = new lib.peng333();
	this.instance.setTransform(90.2,51.2,0.77,0.77,0,0,59,148.2,50.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:148.5,regY:50.3,scaleX:1,scaleY:1,skewY:-10,x:154.2,y:-3.5,alpha:1},15,cjs.Ease.get(1)).to({regY:50.2,skewY:0,y:8},8,cjs.Ease.get(1)).wait(88).to({skewY:5},10).to({regX:148.6,regY:49.9,scaleX:0.94,scaleY:0.94,skewY:-15,x:146.4,y:-18.6},8).to({regX:148.5,regY:50.4,scaleX:0.68,scaleY:0.68,skewY:-96,x:49.5,y:-74.1,alpha:0},7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(31.4,-85.6,40.3,144.1);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_273 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(273).call(this.frame_273).wait(27));

	// Layer 3
	this.instance = new lib.Symbol244();
	this.instance.setTransform(90.2,51.2,0.77,0.77,0,0,59,148.2,50.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:148.5,regY:50.3,scaleX:1,scaleY:1,skewY:-10,x:154.2,y:-3.5,alpha:1},15,cjs.Ease.get(1)).to({regY:50.2,skewY:0,y:8},8,cjs.Ease.get(1)).wait(85).to({skewY:5},11).to({regX:148.6,regY:49.9,scaleX:0.94,scaleY:0.94,skewY:-15,x:146.4,y:-18.6},8).to({regX:148.5,regY:50.4,scaleX:0.68,scaleY:0.68,skewY:-96,x:49.5,y:-74.1},7).to({regX:148.2,regY:50.6,scaleX:0.77,scaleY:0.77,skewY:59,x:90.2,y:51.2},1).to({regX:148.5,regY:50.3,scaleX:1,scaleY:1,skewY:-10,x:154.2,y:-3.5},15,cjs.Ease.get(1)).to({regY:50.2,skewY:0,y:8},8,cjs.Ease.get(1)).wait(115).to({skewY:5},11).to({regX:148.6,regY:49.9,scaleX:0.94,scaleY:0.94,skewY:-15,x:146.4,y:-18.6},8).to({regX:148.5,regY:50.4,scaleX:0.68,scaleY:0.68,skewY:-96,x:49.5,y:-74.1,alpha:0},7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(31.4,-85.6,40.3,144.1);


(lib.also = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_112 = function() {
		this.stop();
	}
	this.frame_119 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(112).call(this.frame_112).wait(7).call(this.frame_119).wait(1));

	// erdekel
	this.instance = new lib.Tween144("synched",0);
	this.instance.setTransform(231.3,97.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(33).to({_off:false},0).to({x:86,y:97.5},15,cjs.Ease.get(1)).to({startPosition:0},64).to({y:175.5},7).wait(1));

	// Layer 5
	this.instance_1 = new lib.Tween644("synched",0);
	this.instance_1.setTransform(-216,101);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(20).to({_off:false},0).to({x:-111},13,cjs.Ease.get(1)).to({startPosition:0},79).to({y:179},7).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("A6EGrIjFtVMA6TAAbIAAM6g");
	this.shape.setTransform(-10.2,188.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.125)").s().p("A5xHMIhLjDIiAqAQEthWEuACQGCAOGVALQHRALHWAHQHGAGG5ABQDnAADdgCQAQBcAMBbIABJqInCBGg");
	this.shape_1.setTransform(-9,185.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.251)").s().p("A5dHvIhkinIhvqJIAAAAQECivEEACQF8AZGjATQHWASHbALQHRAJG3gBQDtgBDagGQAhBMAYBLIADJwImBCMg");
	this.shape_2.setTransform(-7.9,181.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.376)").s().p("A5JISIh9iLIhdqSIAAgBQDWkHDaACQF3AjGxAbQHZAaHiAOQHcANG0gDQD1gDDXgKQAwA9AkA6IAEJ3Ik/DSg");
	this.shape_3.setTransform(-6.8,178.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0.502)").s().p("A41I1IiWhvIhMqcIAAAAQCrlgCwACQFxAtG/AjQHdAjHoAQQHnARGygGQD8gEDUgNQBAAtAwApIAGJ+Ij+EYg");
	this.shape_4.setTransform(-5.6,174.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0.624)").s().p("A4iJYIiuhTIg6qlIAAgBQB/m4CGACQFrA4HOArQHfAqHvAUQHyAUGwgIQECgFDRgSQBRAeA8AYIAHKEIi8Ffg");
	this.shape_5.setTransform(-4.5,171.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.749)").s().p("A4OJ7IjHg3IgpquIAAgBQBUoRBcACQFmBCHbAzQHiAyH2AXQH9AYGugKQEJgHDOgVQBhANBIAIIAJKLIh7Glg");
	this.shape_6.setTransform(-3.3,167.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.875)").s().p("A36KfIjggdIgXq2IAAgBQAopqAzABQFfBOHqA7QHlA5H9AbQIIAaGsgLQEPgIDLgZQBxgCBVgKIAJKSIg4Hsg");
	this.shape_7.setTransform(-2.2,164.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("A7jLCQgEligClgQgDrCAJACQFaBXH3BDQHpBBIDAeQITAfGqgPQHKgQD2hCIAUTLg");
	this.shape_8.setTransform(-0.7,160.7);
	this.shape_8._off = true;

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("A7jLBQgElhgClgQgDrDAJADQFaBXH3BDQHpBBIDAeQITAfGqgPQHKgQD2hCIAUTKg");
	this.shape_9.setTransform(-0.7,157.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("A7jLCQgEligClgQgDrCAJACQFaBXH3BDQHpBBIDAeQITAeGqgOQHKgQD2hCIAUTLg");
	this.shape_10.setTransform(-0.7,155.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("A7jLCQgEligClgQgDrCAJABQFaBYH3BDQHpBBIDAeQITAfGqgPQHKgQD2hCIAUTLg");
	this.shape_11.setTransform(-0.7,149.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("A7jLCIAAgDQgElggClfQgDrCAJACIACAAQFbBTH0BBQHYA8HwAeIAkACQITAfGqgNQHIgOD4g9IAUTLg");
	this.shape_12.setTransform(-0.7,130.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("A7jLBIAAgBQgElhgClfQgDrBAJABIACAAQFeBPHxA/QHYA6HxAeIAkACQITAfGpgLQHGgLD6g6IAUTKg");
	this.shape_13.setTransform(-0.7,131);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("A7jLCIAAgCQgElhgClfQgDrAAJgBIACAAQFgBNHvA8QHYA4HxAeIAkACQITAeGpgJQHFgJD7g1IAUTLg");
	this.shape_14.setTransform(-0.7,131.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("A7jLBIAAgBQgElhgClfIAAAAQgDrAAJgBIABAAQFjBJHuA6QHXA1HyAeIAkACQISAeGpgGQHDgID9gwIAUTKg");
	this.shape_15.setTransform(-0.7,131.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("A7jLCIAAgCQgElhgClfIAAAAQgDq/AJgBIABAAQFlBEHsA4QHXAzHyAeIAkACQITAdGogEQHBgFD/gsIAUTLg");
	this.shape_16.setTransform(-0.7,132.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("A7jLCIAAgCQgElggClgIAAAAQgDq/AJgBIABAAQFnBBHqA1QHXAyHzAdIAkACQISAdGpgCQG+gDEBgoIAUTLg");
	this.shape_17.setTransform(-0.7,132.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("A7jLBIAAgBQgElhgClfIAAAAQgDq9AJgDIABgBQFpA+HoAzQHXAvHzAdIAkACQITAeGoAAQG8gCEDgjIAUTKg");
	this.shape_18.setTransform(-0.7,132.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("A7jLCIAAgCQgElhgClfQgDq9AJgDIABAAQFsA4HmAxQHWAuHzAdIAkACQITAcGoACQG6ABEFgeIAUTLg");
	this.shape_19.setTransform(-0.7,133.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("A7jLCIAAgCQgElhgClfQgDq8AJgFIABAAQFuA2HkAuQHWArH0AcIAkACQISAeGoAEQG4ADEHgaIAUTLg");
	this.shape_20.setTransform(-0.7,133.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("A7jLBIAAgBQgElhgClfQgDq8AJgEIABAAQFwAxHiAsQHWApH0AcIAkACQITAdGnAHQG2AEEJgVIAUTKg");
	this.shape_21.setTransform(-0.7,134.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("A7iLBIgBgBQgElhgClfIAAAAQgDq7AJgFIABgBQFyAvHgApQHWAnH1AcIAkACQISAdGnAIQG0AHELgRIAUTKg");
	this.shape_22.setTransform(-0.7,134.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("A7iLCIgBgBQgElhgClgIAAAAQgDq7AJgFIABAAQF0ApHfAoQHVAlH1AbIAkACQITAdGmALQGyAIENgMIAUTLg");
	this.shape_23.setTransform(-0.7,134.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("A7iLBIgBgBQgElhgClfIAAAAQgDq6AJgHIABAAQF2AmHdAmQHVAiH2AcIAkACQISAcGnANQGvALEPgIIAUTKg");
	this.shape_24.setTransform(-0.7,135.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("A7iLCIgBgBQgEligClfIAAAAQgDq6AJgGIABAAQF5AiHaAiQHWAhH1AbIAkACQITAcGmAPQGuANEQgDIAUTLg");
	this.shape_25.setTransform(-0.7,135.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("A7iLCIgBgCQgElggClgIAAAAQgEq4AKgIIABAAQF7AeHYAhQHWAeH2AbIAkACQISAcGmARQGsAQESAAIAUTLg");
	this.shape_26.setTransform(-0.7,136);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("A7iLCIgBgBQgElhgClgIAAAAQgEq4AKgIIABgBQF9AbHWAeQHWAdH2AbIAkACQISAcGmATQGqAREUAFIAUTLg");
	this.shape_27.setTransform(-0.7,136.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("A7iLBIgBgBQgElggClgIAAAAQgEq4AKgIIABAAINUAyIPMA1IAkACIO3AxQGoAUEWAJIAUTKg");
	this.shape_28.setTransform(-0.7,136.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("A7iLBIgBAAQgElggClhIAAAAQgEq2AKgKIAAgBQGCAUHTAZIPMAzIAkACIO3AzIK+AjIAUTKg");
	this.shape_29.setTransform(-0.7,137.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("A7iLCIgBgBQgElhgClgIAAAAQgEq2AKgKIAAAAQGEAPHRAXQHVAWH4AbIAkACQISAaGkAaQGkAXEaATIAUTLg");
	this.shape_30.setTransform(-0.7,137.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("A7iLBIgBAAQgElggClhIAAAAQgEq1AKgLIAAgBQGGANHPAUQHVAUH4AaIAkABQISAcGlAbQGhAaEcAXIAUTKg");
	this.shape_31.setTransform(-0.7,138);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("A7iLCIgBgBQgElggClhIAAAAQgEq1AKgLIAAAAQGJAHHNATQHUARH5AaIAkACQIRAbGlAdQGfAdEeAbIAUTLg");
	this.shape_32.setTransform(-0.7,138.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("A7iLBIgBAAQgElhgClgIAAAAQgEq0AKgNIAAAAQGLAFHLAPQHUAQH5AZIAkACQISAcGkAfQGdAeEgAgIAUTKg");
	this.shape_33.setTransform(-0.7,138.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("A7iLBIgBAAQgElhgClgIAAAAQgEqzAKgNIAAgBQGNABHJAOQHUANH5AZIAkACQISAcGkAhQGbAgEiAkIAUTKg");
	this.shape_34.setTransform(-0.7,139.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("A7iLCIgBgBQgElggClhIAAAAQgEqyAKgOIAAAAQGPgEHHAMQHUALH6AZIAkACQISAbGjAjQGZAjEkAoIAUTLg");
	this.shape_35.setTransform(-0.7,139.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("A7hLDIgCAAQgElhgClgIAAgBQgEqxAKgOIAAgBQGRgHHGAJQHTAJH6AZIAkACQISAbGjAlQGXAkEmAuIAUTKg");
	this.shape_36.setTransform(-0.7,139.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("A7hLFIgCgBQgElggClhIAAgBQgEqwAKgPQGTgLHEAGQHTAHH7AZIAkACQIRAaGjAoQGWAmEnAyIAUTLg");
	this.shape_37.setTransform(-0.7,140);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("A7hLHIgCAAQgElggClhIAAgBQgEqwAKgPIAAgBQGWgOHBAEQHTAFH7AYIAkACQISAbGjApQGTApEpA2IAUTKg");
	this.shape_38.setTransform(-0.7,140.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("A7jLKQgElhgClhQgErAAKAAQNCgmPkAwQQmAzJuB6IAUTLg");
	this.shape_39.setTransform(-0.7,140.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("A7jLIQgElhgClhQgErAAKAAQNQggPXAwQQmAzJtB0IAUTLg");
	this.shape_40.setTransform(-0.7,140.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("A7jLGQgElhgClhQgErAAKAAQNegaPLAwQQmAzJrBuIAUTLg");
	this.shape_41.setTransform(-0.7,139.9);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("A7jLEQgElhgClhQgEq/AKgBQNrgTO/AvQQmA0JqBoIAUTKg");
	this.shape_42.setTransform(-0.7,139.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("A7jLDQgElhgClhQgEq/AKgBQN5gNOzAuQQlA1JpBiIAUTKg");
	this.shape_43.setTransform(-0.7,139.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("A7jLCQgElhgClhQgErAAKAAQOHgHOnAuQQkA1JoBcIAUTKg");
	this.shape_44.setTransform(-0.7,139.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("A7jLCQgElhgClhQgErAAKAAQOUgCObAuQQkA1JnBWIAUTLg");
	this.shape_45.setTransform(-0.7,138.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("A7jLBQgElhgClgQgErAAKAAQOiAEOPAtQQjA2JmBQIAUTKg");
	this.shape_46.setTransform(-0.7,138.6);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("A7jLCQgEligClgQgErAAKAAQOwAKOCAuQQjA1JlBKIAUTLg");
	this.shape_47.setTransform(-0.7,138.3);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("A7jLCQgElhgClhQgErAAKAAQO9AQN3AtQQjA3JjBDIAUTLg");
	this.shape_48.setTransform(-0.7,137.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("A7jLCQgElhgClhQgErAAKAAQPLAWNqAsQQjA3JiA+IAUTLg");
	this.shape_49.setTransform(-0.7,137.6);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("A7jLCQgElhgClhQgErAAKgBQPZAdNeAsQQiA4JhA3IAUTLg");
	this.shape_50.setTransform(-0.7,137.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("A7jLBQgElhgClgQgErAAKgBQPmAjNSAsQQiA3JgAyIAUTKg");
	this.shape_51.setTransform(-0.7,136.9);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("A7jLBQgElhgClgQgErAAKgBQP0AoNGAtQQhA4JfArIAUTKg");
	this.shape_52.setTransform(-0.7,136.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("A7jLBQgElhgClgQgErBAKAAQQCAvM6ArQQgA4JeAmIAUTKg");
	this.shape_53.setTransform(-0.7,136.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("A7jLBQgElggClhQgErBAKAAQQPA0MuAsIZ9BYIAUTKg");
	this.shape_54.setTransform(-0.7,135.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("A7jLBQgElggClhQgErBAKABIc/BlQQfA5JcAZIAUTKg");
	this.shape_55.setTransform(-0.7,135.4);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("A7jLCQgEligClgQgErBAKABQQrA/MVAsQQgA4JaAUIAUTLg");
	this.shape_56.setTransform(-0.7,135.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("A7jLCQgElhgClhQgErBAKABQQ4BGMKAqQQfA6JZANIAUTLg");
	this.shape_57.setTransform(-0.7,134.7);
	this.shape_57._off = true;

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("A7jLCQgEligClgQgErBAKABQQ4BGMKAqQQfA6JZANIAUTLg");
	this.shape_58.setTransform(-0.7,145.9);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("A7jLBQgElggClhQgErBAKABQQ4BFMKArQQfA5JZAOIAUTKg");
	this.shape_59.setTransform(-0.7,157);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("A7jLBQgElggClhQgErBAKAAQQ4BHMKAqQQfA6JZANIAUTKg");
	this.shape_60.setTransform(-0.7,168.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9,p:{y:157.9}}]},1).to({state:[{t:this.shape_10,p:{y:155.2}}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_11,p:{y:149.6}}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9,p:{y:141.3}}]},1).to({state:[{t:this.shape_10,p:{y:138.5}}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_11,p:{y:133}}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58,p:{y:145.9}}]},1).to({state:[{t:this.shape_59,p:{y:157}}]},1).to({state:[{t:this.shape_60,p:{y:168.2}}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58,p:{y:190.4}}]},1).to({state:[{t:this.shape_59,p:{y:201.6}}]},1).to({state:[{t:this.shape_60,p:{y:212.7}}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(8).to({_off:false},0).to({_off:true},1).wait(2).to({_off:false,y:152.4},0).to({_off:true},1).wait(1).to({_off:false,y:146.8},0).wait(1).to({y:144.1},0).to({_off:true},1).wait(2).to({_off:false,y:135.7},0).to({_off:true},1).wait(1).to({_off:false,y:130.2},0).to({_off:true},1).wait(100));
	this.timeline.addTween(cjs.Tween.get(this.shape_57).wait(65).to({_off:false},0).wait(47).to({_off:true},1).wait(3).to({_off:false,y:179.3},0).to({_off:true},1).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-196.8,145.8,373.3,85.5);


// stage content:



(lib.master_upc_internet_q2_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		exportRoot.hl_mc.gotoAndStop(0);
		exportRoot.erdekel.gotoAndStop(0);
		exportRoot.p1.gotoAndStop(0);
		exportRoot.p2.gotoAndStop(0);
		
		var frequency=3;
		stage.enableMouseOver(frequency);
		this.jogihit.on("rollover",fl_MouseOverHandler_32);
		
		this.jogihit.on("rollout",fl_MouseOverHandler_33);
		function fl_MouseOverHandler_32()
		{
		    exportRoot.jogi.gotoAndPlay(2);
		}
		
		function fl_MouseOverHandler_33()
		{
		    exportRoot.jogi.gotoAndPlay(11);
		}
	}
	this.frame_145 = function() {
		exportRoot.hl_mc.play();
	}
	this.frame_258 = function() {
		exportRoot.hl_mc.play();
		exportRoot.erdekel.play();
		exportRoot.p1.play();
		exportRoot.p2.play();
		this.stop();
	}
	this.frame_259 = function() {
		exportRoot.hl_mc.play();
		exportRoot.erdekel.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(145).call(this.frame_145).wait(113).call(this.frame_258).wait(1).call(this.frame_259).wait(37));

	// hit
	this.jogihit = new lib.Symbol544();
	this.jogihit.setTransform(301.5,180.6,1,0.464,0,0,0,25,41.1);
	this.jogihit._off = true;
	new cjs.ButtonHelper(this.jogihit, 0, 1, 2, false, new lib.Symbol544(), 3);

	this.timeline.addTween(cjs.Tween.get(this.jogihit).wait(258).to({_off:false},0).wait(38));

	// jogi
	this.jogi = new lib.Symbol444();
	this.jogi.setTransform(290.5,227.9,1,1,0,0,0,10.5,5.5);
	this.jogi._off = true;

	this.timeline.addTween(cjs.Tween.get(this.jogi).wait(258).to({_off:false},0).wait(38));

	// HL
	this.hl_mc = new lib.hl();
	this.hl_mc.setTransform(148.7,59.2,0.7,0.7,0,0,0,186.5,39.7);

	this.timeline.addTween(cjs.Tween.get(this.hl_mc).wait(296));

	// p2
	this.p2 = new lib.p2();
	this.p2.setTransform(41.3,134.7,1.288,1.288,0,0,0,17.1,5);

	this.timeline.addTween(cjs.Tween.get(this.p2).wait(296));

	// p1
	this.p1 = new lib.p1();
	this.p1.setTransform(146.9,143.3,1.221,1.22,0,0,0,7.2,7.5);

	this.timeline.addTween(cjs.Tween.get(this.p1).wait(296));

	// also
	this.erdekel = new lib.also();
	this.erdekel.setTransform(165,145,1,1,0,0,0,15,23);

	this.timeline.addTween(cjs.Tween.get(this.erdekel).wait(296));

	// slide3
	this.instance = new lib.upc_mobil_banner_640x360();

	this.instance_1 = new lib.Tween12("synched",0);
	this.instance_1.setTransform(320,180);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},258).to({state:[{t:this.instance_1}]},16).to({state:[{t:this.instance_1}]},21).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(274).to({_off:false},0).to({alpha:0},21).wait(1));

	// slide2
	this.instance_2 = new lib.Tween3("synched",0);
	this.instance_2.setTransform(715.1,223.6,2.35,2.35,0,0,0,0,-0.3);
	this.instance_2.alpha = 0.281;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(124).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1,x:320,y:180,alpha:1},21,cjs.Ease.get(1)).to({startPosition:0},112).to({_off:true},1).wait(38));

	// slide1
	this.instance_3 = new lib.Tween2("synched",0);
	this.instance_3.setTransform(314,589.7,1.87,3.37);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({startPosition:0},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,x:320,y:180},21,cjs.Ease.get(1)).to({startPosition:0},65).to({startPosition:0},14).to({startPosition:0},14).to({_off:true},1).wait(150).to({_off:false,scaleX:1.87,scaleY:3.37,x:314,y:589.7},0).wait(22));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-292.7,103.7,849.7,861.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;